Repository openshift/cluster-ingress-operator, pull requests merged in 2018-09, with the labels that each got.

#18 Support multiple routers
  assets/router/daemonset.yaml
  assets/router/service-cloud.yaml
  deploy/cr.yaml
  pkg/apis/ingress/v1alpha1/types.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/L

#15 Add clean option to Makefile
  HACKING.md
  Makefile
  images/cluster-ingress-operator/Dockerfile
Labels: approved, lgtm, size/M

#19 Do not duplicate default values in yaml
  Makefile
  assets/router/daemonset.yaml
  assets/router/service-cloud.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#22 Assets cleanup: represent router cluster role concisely
  assets/router/cluster-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#21 Add operator manifest
  HACKING.md
  deploy/cluster-ingress-operator.yaml
Labels: approved, lgtm, size/M

#23 Simplify running integration tests
  HACKING.md
  Makefile
  test/integration/integration_test.go
Labels: approved, lgtm, size/L

#24 Add Namespace for Cluster Ingress Operator
  deploy/namespace.yaml
Labels: approved, lgtm, size/XS

#25 Set deployment order
  deploy/01_namespace.yaml
  deploy/02_crd.yaml
  deploy/03_rbac.yaml
  deploy/04_cluster-ingress-operator.yaml
  deploy/05_cr.yaml
Labels: approved, lgtm, size/L

#28 Rename deploy directory
  deploy/cluster-ingress-operator.yaml
  deploy/cr.yaml
  deploy/crd.yaml
  deploy/namespace.yaml
  deploy/rbac.yaml
  images/cluster-ingress-operator/Dockerfile
  manifests/01_namespace.yaml
  manifests/02_crd.yaml
  manifests/03_rbac.yaml
  manifests/04_cluster-ingress-operator.yaml
  test/integration/integration_test.go
Labels: approved, lgtm, size/L

#30 Cleanup unused junk
  .gitignore
  tmp/build/Dockerfile
  tmp/build/build.sh
  tmp/build/docker_build.sh
  tmp/codegen/boilerplate.go.txt
  tmp/codegen/update-generated.sh
Labels: approved, lgtm, size/M

#32 Update operator image spec
  manifests/04_cluster-ingress-operator.yaml
Labels: approved, lgtm, size/XS

#34 Do not use 'operator' name for router cluster role and role bindings
  assets/router/cluster-role-binding.yaml
  assets/router/cluster-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#31 Updated docs to match resource files in manifests dir
  HACKING.md
  manifests/04_cluster-ingress-operator.yaml
Labels: approved, lgtm, size/S

#29 Handle delete events
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#36 Add examples directory
  examples/cr.yaml
Labels: approved, lgtm, size/XS

#39 Honor ClusterIngress node selector and namespace selector
  assets/router/cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/M
