Repository openshift/cluster-ingress-operator, pull requests merged in 2018-10, with the labels that each got.

#42 Fix integration tests
  test/integration/integration_test.go
Labels: approved, lgtm, size/XS

#43 Integrate operator with CVO
  images/cluster-ingress-operator/Dockerfile
  manifests/00-cluster-role.yaml
  manifests/01-cluster-role-binding.yaml
  manifests/01-role-binding.yaml
  manifests/01-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/L

#44 Owner ref for ingress service should only call sdk.Get() on ds if needed.
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#45 Fix installation in latest 4.0 environment
  assets/router/daemonset.yaml
  assets/router/namespace.yaml
  images/cluster-ingress-operator/Dockerfile
  manifests/00-namespace.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#46 Setup ingress out-of-box using the cluster install config
  assets/defaults/cluster-ingress.yaml
  cmd/cluster-ingress-operator/main.go
  manifests/00-cluster-role.yaml
  manifests/01-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
  pkg/util/config.go
  pkg/util/config_test.go
  pkg/util/testhelper.go
Labels: approved, lgtm, size/L

#49 Refactor to level driven design
  cmd/cluster-ingress-operator/main.go
  pkg/stub/handler.go
  pkg/util/slice/slice.go
Labels: approved, lgtm, size/L

#50 Add image refs
  manifests/image-references
Labels: approved, lgtm, size/XS

#51 Revamp the integration tests
  HACKING.md
  Makefile
  hack/release-local.sh
  hack/test-integration.sh
  hack/uninstall.sh
  pkg/manifests/bindata.go
  test/assets/app-ingress/namespace.yaml
  test/assets/app-ingress/route-default.yaml
  test/assets/app-ingress/route.yaml
  test/assets/cluster-ingress-default.yaml
  test/assets/cluster-ingress-internal.yaml
  test/integration/integration_test.go
  test/integration/test_ingress.go
  test/manifests/bindata.go
  test/manifests/manifests.go
Labels: approved, lgtm, size/XL

#52 Rename operator and router namespaces
  assets/defaults/cluster-ingress.yaml
  assets/router/cluster-role-binding.yaml
  assets/router/cluster-role.yaml
  assets/router/daemonset.yaml
  assets/router/namespace.yaml
  assets/router/service-account.yaml
  assets/router/service-cloud.yaml
  hack/uninstall.sh
  manifests/00-cluster-role.yaml
  manifests/00-namespace.yaml
  manifests/01-cluster-role-binding.yaml
  manifests/01-role-binding.yaml
  manifests/01-role.yaml
  manifests/01-service-account.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
  test/assets/app-ingress/namespace.yaml
  test/integration/test_ingress.go
  test/manifests/bindata.go
Labels: approved, lgtm, size/L

#56 release-local.sh: Fix cp command for manifests
  hack/release-local.sh
Labels: approved, lgtm, size/XS
