Repository openshift/cluster-ingress-operator, pull requests merged in 2018-12, with the labels that each got.

#71 Get ingress domain from ingress config
  Gopkg.lock
  cmd/cluster-ingress-operator/main.go
  manifests/00-cluster-role.yaml
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/config.go
  pkg/stub/handler.go
  pkg/util/config.go
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/stringsource.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#73 Improve docs
  HACKING.md
  README.md
Labels: approved, lgtm, size/M

#76 Replace router DaemonSet with Deployment
  assets/router/deployment.yaml
  cmd/cluster-ingress-operator/main.go
  manifests/00-cluster-role.yaml
  manifests/01-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
  pkg/stub/status.go
  pkg/stub/status_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#80 Assign system-cluster-critical priority to operator and component
  assets/router/deployment.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#83 replace tectonicClusterID tag with openshiftClusterID
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/XS

#81 Add UserDefinedClusterIngressHA
  pkg/apis/ingress/v1alpha1/clusteringress_types.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/M

#88 Consume cluster ID from config.openshift.io
  cmd/cluster-ingress-operator/main.go
  manifests/00-cluster-role.yaml
  pkg/util/config.go
Labels: approved, lgtm, size/S

#87 Simplify multi-namespace controller setup
  Makefile
  hack/uninstall.sh
  manifests/02-deployment.yaml
  pkg/operator/controller/controller.go
  pkg/operator/manager/manager.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#90 Fix selector for internal router service, so that it is correctly populated
  pkg/manifests/manifests.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#92 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
