Repository openshift/cluster-ingress-operator, pull requests merged in 2018-11, with the labels that each got.

#58 Do no generate bindata for manifests used by CVO
  hack/update-generated-bindata.sh
  pkg/manifests/bindata.go
  pkg/util/clusteroperator/status_test.go
Labels: approved, lgtm, size/L

#57 release-local.sh: Use Buildah if available.
  hack/release-local.sh
Labels: approved, lgtm, size/XS

#65 Use UpdateStatus to update status
  Gopkg.lock
  cmd/cluster-ingress-operator/main.go
  pkg/stub/handler.go
  pkg/stub/status.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/cluster_id.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/cvoconfig.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/register.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/types.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/url.go
  vendor/github.com/openshift/cluster-version-operator/pkg/apis/clusterversion.openshift.io/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/clientset.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/doc.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/clusterversion.openshift.io_client.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/cvoconfig.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/doc.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/generated_expansion.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/clusteroperator.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/doc.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/generated_expansion.go
  vendor/github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/operatorstatus.openshift.io_client.go
Labels: approved, lgtm, size/XXL

#64 Add baseline end-to-end tests
  Makefile
  manifests/00-cluster-role.yaml
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#67 Add HTTPS endpoint to router service
  assets/router/service-cloud.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#72 Make router image configurable
  Makefile
  assets/router/daemonset.yaml
  cmd/cluster-ingress-operator/main.go
  hack/test-integration.sh
  hack/update-generated-bindata.sh
  hack/verify-generated-bindata.sh
  manifests/02-deployment.yaml
  manifests/image-references
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/config.go
  test/assets/app-ingress/deployment.yaml
  test/assets/app-ingress/namespace.yaml
  test/assets/app-ingress/route.yaml
  test/assets/app-ingress/service.yaml
  test/integration/integration_test.go
  test/integration/test_ingress.go
  test/manifests/bindata.go
  test/manifests/manifests.go
Labels: approved, lgtm, size/XL

#69 Delete unused code for install config
  pkg/stub/handler.go
  pkg/util/testhelper.go
Labels: approved, lgtm, size/L

#68 [NE-68] Add support for cluster ingress edge encryption support
  assets/router/daemonset.yaml
  assets/router/service-internal.yaml
  pkg/apis/ingress/v1alpha1/types.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L
