Repository openshift/cluster-ingress-operator, pull requests merged in 2019-08, with the labels that each got.

#279 dns/azure: Use absolute domain name in unit tests
  pkg/dns/azure/dns_test.go
Labels: approved, lgtm, size/XS

#281 status: add dnsrecords to related objects
  pkg/operator/controller/status/controller.go
Labels: approved, lgtm, size/M

#282 status: compute ingresscontroller availability from deployment conditions
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: approved, lgtm, size/L

#283 Bug 1698562: status: introduce ingresscontroller degraded condition
  assets/router/deployment.yaml
  hack/run-local.sh
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#284 Fix admission to log rejections and not retry
  pkg/operator/controller/ingress/controller.go
Labels: approved, lgtm, size/M

#286 dns: always publish records to configured DNS zones
  pkg/operator/controller/dns/controller.go
Labels: approved, lgtm, size/S

#287 Bug 1740441: manifests: make credentialsrequest names consistent
  manifests/00-ingress-credentials-request.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#289 Bug 1740595: ensureServiceMonitor: Update resource if needed
  manifests/00-cluster-role.yaml
  pkg/operator/controller/ingress/metrics.go
  pkg/operator/controller/ingress/monitoring.go
  pkg/operator/controller/ingress/monitoring_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#288 Set default role for minted credentials to Contributor
  manifests/00-ingress-credentials-request.yaml
Labels: approved, lgtm, size/XS

#293 Add unsupported annotation for enabling access logs
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/rsyslog_configmap.go
  pkg/operator/controller/names.go
Labels: approved, lgtm, size/L
