Repository openshift/cluster-ingress-operator, pull requests merged in 2019-02, with the labels that each got.

#113 Renamed ingress ClusterOperator name from 'openshift-ingress-operator' to 'ingress'
  pkg/operator/controller/controller.go
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/S

#110 Put router-ca configmap in openshift-config-managed iff needed
  manifests/00-cluster-role.yaml
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#116 Add credentials request for AWS.
  manifests/00-ingress-credentials-request.yaml
Labels: approved, lgtm, size/S

#120 Increase default clusteringress's replicas to 2
  assets/defaults/cluster-ingress.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#124 controller: refactor event triggering
  pkg/manifests/manifests.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#123 Requeue requests during controller reconciliation if needed
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_lb.go
Labels: approved, lgtm, size/L

#118 Set pathlen constraint on router-ca
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_ca_configmap.go
  pkg/operator/controller/controller_ca_secret.go
  pkg/operator/controller/controller_default_certificate.go
Labels: approved, lgtm, size/XL

#127 controller: clean up error handling
  hack/uninstall.sh
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_lb.go
Labels: approved, lgtm, size/L

#119 manifests: Add ClusterOperator resource
  manifests/03-cluster-operator.yaml
Labels: approved, lgtm, size/XS

#129 Updates ingress clusteroperator name in hack/uninstall
  hack/uninstall.sh
Labels: approved, lgtm, size/XS

#126 Refactors Logging to use the zapr implementation of go-logr/logr
  Gopkg.lock
  cmd/cluster-ingress-operator/main.go
  pkg/dns/aws/dns.go
  pkg/log/log.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_ca_configmap.go
  pkg/operator/controller/controller_ca_secret.go
  pkg/operator/controller/controller_default_certificate.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/controller/controller_service_monitor.go
  pkg/operator/controller/status.go
  pkg/operator/operator.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_aix.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: approved, lgtm, size/XXL

#130 Fix ingress domain and high availability defaulting and status reporting
  cmd/cluster-ingress-operator/main.go
  pkg/apis/ingress/v1alpha1/clusteringress_types.go
  pkg/apis/ingress/v1alpha1/zz_generated.deepcopy.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/config/config.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_default_certificate.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/controller/controller_router_deployment.go
  pkg/operator/controller/controller_router_deployment_test.go
  pkg/operator/controller/controller_service_monitor.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/XXL

#136 controller: try harder to publish status when errors occur
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/M

#135 dns/aws: include operator version in UserAgent for AWS API calls
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/XS

#138 dns/aws: cache load balancer hosted zones
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/M

#133 Improves zapr logger contextual information
  pkg/dns/aws/dns.go
  pkg/log/log.go
  pkg/operator/controller/controller.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/S

#137 Treat HA configuration as immutable
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/controller/controller_router_deployment.go
  pkg/operator/controller/controller_router_deployment_test.go
Labels: approved, lgtm, size/L

#132 Process as much as possible during reconcile and requeue in case of any errors
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_default_certificate.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/controller/controller_router_deployment.go
  pkg/operator/controller/controller_service_monitor.go
Labels: approved, lgtm, size/L

#134 Adds info log msg indicating ns/secret used by DNSManager
  cmd/cluster-ingress-operator/main.go
Labels: approved, lgtm, size/XS

#140 Introduce certificate controller
  Gopkg.lock
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/controller.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#141 controller/certificate: move cert generation to cert controller
  hack/uninstall.sh
  pkg/operator/controller/certificate/ca.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/certificate/default_cert.go
  pkg/operator/controller/controller.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#142 controller/certificate: relocate CA publishing
  hack/uninstall.sh
  manifests/00-cluster-role.yaml
  pkg/log/log.go
  pkg/operator/controller/certificate/ca.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/certificate/default_cert.go
  pkg/operator/controller/certificate/publish_ca.go
  pkg/operator/controller/certificate/publish_ca_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/names.go
Labels: approved, lgtm, size/L
