Repository openshift/cluster-ingress-operator, pull requests merged in 2019-04, with the labels that each got.

#183 Adds IngressController CRD Validation & Generation
  Makefile
  manifests/00-custom-resource-definition.yaml
Labels: approved, lgtm, size/M

#196 Do not need to call manifests.RouterDeployment() in ensureRouterDeleted()
  pkg/operator/controller/controller_router_deployment.go
Labels: approved, lgtm, size/XS

#197 Adds Watch error handling
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#199 Fix 'strategy' location in manifests/02-deployment.yaml
  manifests/02-deployment.yaml
Labels: approved, lgtm, size/XS

#194 Bug 1696168: Use 'ingresscontroller.operator.openshift.io' prefix for ingress controller labels
  Dockerfile
  Dockerfile.rhel7
  HACKING.md
  Makefile
  assets/router/deployment.yaml
  assets/router/service-cloud.yaml
  assets/router/service-internal.yaml
  cmd/ingress-operator/main.go
  hack/uninstall.sh
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/operator/controller/certificate-publisher/publish_certs_test.go
  pkg/operator/controller/certificate/ca.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/certificate/default_cert.go
  pkg/operator/controller/certificate/publish_ca.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_internal_service.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/controller/controller_router_deployment.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#204 Bug 1699488: Fixes Ingress ClusterOperator Initial Status
  pkg/operator/controller/status.go
Labels: approved, lgtm, size/S

#202 Adds Toleration Support
  Gopkg.lock
  Gopkg.toml
  manifests/00-custom-resource-definition.yaml
  pkg/operator/controller/controller_router_deployment.go
  pkg/operator/controller/controller_router_deployment_test.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#211 Report available=false if domain is already in use
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/S

#201 Minor Operator Status Refactor
  cmd/ingress-operator/main.go
  pkg/operator/controller/status.go
Labels: approved, lgtm, size/M

#212 record log into pod status on error
  assets/router/deployment.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#213 Bug 1701462: deploymentConfigChanged: Fix deleting tolerations
  pkg/operator/controller/controller_router_deployment.go
Labels: approved, lgtm, size/XS

#214 start-build.sh: Don't patch operator IMAGE env var
  hack/start-build.sh
Labels: approved, lgtm, size/XS

#203 Delete registration of client-go GCP auth plug-in
  cmd/ingress-operator/main.go
Labels: approved, lgtm, size/XS

#216 Moves Operator Failing status to Degraded
  Gopkg.lock
  Gopkg.toml
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#217 Add node-selector annotation to namespace
  manifests/00-namespace.yaml
Labels: approved, lgtm, size/XS

#219 Bug 1701392: Choose an appropriate default deployment strategy for an endpoint publishing strategy
  pkg/operator/controller/controller_router_deployment.go
Labels: approved, lgtm, size/M
