Repository openshift/cluster-ingress-operator, pull requests merged in 2019-01, with the labels that each got.

#93 Optimize private zone discovery
  Gopkg.lock
  pkg/dns/aws/dns.go
  vendor/github.com/aws/aws-sdk-go/aws/arn/arn.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/api.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/doc.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/errors.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/service.go
Labels: approved, lgtm, size/XXL

#95 Make clusteringress scalable
  Gopkg.lock
  assets/defaults/cluster-ingress.yaml
  manifests/00-cluster-role.yaml
  manifests/00-custom-resource-definition.yaml
  pkg/apis/ingress/v1alpha1/clusteringress_types.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/controller/controller.go
  test/e2e/operator_test.go
  vendor/k8s.io/client-go/discovery/cached/memcache.go
  vendor/k8s.io/client-go/scale/client.go
  vendor/k8s.io/client-go/scale/doc.go
  vendor/k8s.io/client-go/scale/interfaces.go
  vendor/k8s.io/client-go/scale/scheme/appsint/doc.go
  vendor/k8s.io/client-go/scale/scheme/appsint/register.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/conversion.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/doc.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/register.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/conversion.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/doc.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/register.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/conversion.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/doc.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/register.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/doc.go
  vendor/k8s.io/client-go/scale/scheme/extensionsint/doc.go
  vendor/k8s.io/client-go/scale/scheme/extensionsint/register.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/conversion.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/doc.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/register.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/register.go
  vendor/k8s.io/client-go/scale/scheme/types.go
  vendor/k8s.io/client-go/scale/scheme/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/scale/util.go
Labels: approved, lgtm, size/XXL

#99 Cope with pagination in private zone discovery
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/M

#100 Improve error handling in private zone discovery
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/XS

#94 [NE-72] Handle updates to ClusterIngress and update a subset of the generated ingress assets
  manifests/00-cluster-role.yaml
  pkg/operator/controller/controller.go
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#102 Set default HA type based on platform
  assets/defaults/cluster-ingress.yaml
  cmd/cluster-ingress-operator/main.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/config/config.go
Labels: approved, lgtm, size/M

#104 Restrict operator to masters
  manifests/02-deployment.yaml
Labels: approved, lgtm, size/XS

#103 docs/readme: Add Bugzilla issue reporting link
  README.md
Labels: approved, lgtm, size/XS

#107 Namespace field not needed for cluster scoped resource
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/XS

#84 Cloud HA strategy should automatically use PROXY support when available.
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#109 Use self-signed default router certificate
  Gopkg.lock
  manifests/00-cluster-role.yaml
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/controller/controller.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
Labels: approved, lgtm, size/XXL

#106 Use credentials from cloud-credential-operator
  cmd/cluster-ingress-operator/main.go
  manifests/01-kube-system-aws-creds-role-binding.yaml
Labels: approved, lgtm, size/S
