Repository openshift/cluster-ingress-operator, pull requests merged in 2019-05, with the labels that each got.

#200 Bug 1704982: Fix updating versions for ingress cluster operator
  cmd/ingress-operator/main.go
  manifests/03-cluster-operator.yaml
  pkg/operator/config/config.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_router_deployment.go
  pkg/operator/controller/controller_router_deployment_test.go
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/XL

#223 Bug 1705100: TestIngressControllerUpdate: Re-get between updates
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#222 Bug 1703943: Make deployment topologies more predictable by prohibiting co-location
  pkg/operator/controller/controller_router_deployment.go
  pkg/operator/controller/controller_router_deployment_test.go
Labels: approved, lgtm, size/L

#225 Bug 1705100: TestIngressControllerScale: Re-get between updates
  test/e2e/operator_test.go
Labels: approved, lgtm, size/XS

#227 Fix hack/release.sh: Skip ClusterOperator resource creation
  hack/release-local.sh
Labels: approved, lgtm, size/XS

#226 Fix tolerations
  manifests/02-deployment.yaml
Labels: approved, lgtm, size/S

#229 Bug 1707085: Update Progressing condition if upgrade happened
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
Labels: approved, lgtm, size/M

#218 BUG 1707477: label the openshift-ingress namespace with its name
  assets/router/namespace.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#228 Cleanup: Remove unnecessary Factory struct from manifests
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/controller/controller.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#220 Minor: Move service monitor name to pkg/operator/controller/names.go
  pkg/operator/controller/controller_service_monitor.go
  pkg/operator/controller/names.go
Labels: approved, lgtm, size/S

#238 Bug 1706576: Eliminate ec2 metadata dependency
  cmd/ingress-operator/main.go
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/M

#233 Don't ignore LastTransitionTime when comparing ingress controller status conditions
  pkg/operator/controller/controller.go
  pkg/operator/controller/ingress_status.go
  pkg/operator/controller/ingress_status_test.go
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
Labels: approved, lgtm, size/L

#234 publishingStrategyTypeForInfra: Add case for Azure
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/XS

#236 Use LoadBalancer publishing for GCP
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/XS

#237 Fix gitignore to exclude operator binary
  .gitignore
Labels: approved, lgtm

#241 Add LoadBalancer status reporting on IngressController
  pkg/operator/controller/controller.go
  pkg/operator/controller/ingress_status.go
  pkg/operator/controller/ingress_status_test.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/XL

#242 add selector to servicemonitor
  pkg/operator/controller/controller_service_monitor.go
Labels: approved, lgtm, size/XS
