Repository openshift/cluster-ingress-operator, pull requests merged in 2019-09, with the labels that each got.

#295 Bug 1747840: dns: add explicit TTL to all wildcard records
  hack/run-local.sh
  pkg/dns/azure/dns.go
  pkg/dns/azure/dns_test.go
  pkg/dns/gcp/provider.go
  pkg/operator/controller/dns/controller.go
  pkg/operator/controller/ingress/dns.go
  pkg/operator/controller/ingress/dns_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#298 ensureWildcardDNSRecord: Fix method name in godoc
  pkg/operator/controller/ingress/dns.go
Labels: approved, lgtm, size/XS

#303 Enable debug support when building/running ingress-operator
  Makefile
  hack/run-local.sh
Labels: approved, lgtm, size/S

#302 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#304 dns/aws: Do not include record in error messages
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/XS
