Repository openshift/cluster-ingress-operator, pull requests merged in 2019-06, with the labels that each got.

#244 Bug 1717494: Refactor client and cache handling
  cmd/ingress-operator/main.go
  hack/uninstall.sh
  pkg/operator/controller/certificate-publisher/controller.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_service_monitor.go
  pkg/operator/controller/status.go
  pkg/operator/operator.go
  pkg/util/restmapper.go
Labels: approved, lgtm, size/L

#245 Surface service-controller LB provisioning failures through status
  manifests/00-cluster-role.yaml
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/controller/ingress_status.go
  pkg/operator/controller/ingress_status_test.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#248 metrics: fix metric registration bug
  pkg/operator/controller/certificate-publisher/controller.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/S

#247 modules: sync go mod tidy / go mod vendor output
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#249 Bug 1717737: status: add related ingresscontrollers to operator status
  pkg/operator/controller/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#251 dns: introduce CRD DNS architecture and DNS status reporting
  Makefile
  cmd/ingress-operator/main.go
  hack/update-generated-crd.sh
  hack/verify-generated-crd.sh
  manifests/00-cluster-role.yaml
  manifests/00-custom-resource-definition-internal.yaml
  pkg/api/v1/register.go
  pkg/api/v1/types.go
  pkg/api/v1/zz_generated.deepcopy.go
  pkg/dns/aws/dns.go
  pkg/dns/azure/dns.go
  pkg/dns/azure/dns_test.go
  pkg/dns/azure/fake_dns.go
  pkg/dns/dns.go
  pkg/manifests/manifests.go
  pkg/operator/client/client.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns.go
  pkg/operator/controller/controller_dns_test.go
  pkg/operator/controller/controller_lb.go
  pkg/operator/controller/dns/controller.go
  pkg/operator/controller/ingress_status.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/scheme/scheme.go
Labels: approved, lgtm, size/XXL

#255 controller: rename some files
  pkg/operator/controller/deployment.go
  pkg/operator/controller/deployment_test.go
  pkg/operator/controller/dns.go
  pkg/operator/controller/dns_test.go
  pkg/operator/controller/internal_service.go
  pkg/operator/controller/load_balancer_service.go
  pkg/operator/controller/monitoring.go
Labels: approved, lgtm, size/XS

#257 Refactors main reconcile loop
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/M

#260 controller: fix AWS internal loadbalancer annotation
  pkg/dns/aws/dns.go
  pkg/operator/controller/load_balancer_service.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#256 Split ingress and status controllers
  cmd/ingress-operator/main.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/dns.go
  pkg/operator/controller/ingress/dns_test.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/monitoring.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/controller/names.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#261 controller/ingress: split namespace and metrics out of main file
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/metrics.go
  pkg/operator/controller/ingress/namespace.go
Labels: approved, lgtm, size/L
