Repository openshift/cluster-ingress-operator, pull requests merged in 2019-12, with the labels that each got.

#331 publish a router-ca that can be used to verify routes in golang clients
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/certificate/publish_ca.go
  pkg/operator/controller/names.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#337 Bug 1781948: Do not wrap errors from syncIngressControllerStatus
  pkg/operator/controller/ingress/controller.go
  pkg/util/retryableerror/retryableerror_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#334 Bug 1765044: Adds proxy support to ingress operator
  cmd/ingress-operator/start.go
  manifests/01-trusted-ca-configmap.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#339 Bug 1783007: Ignore spec.replicas in deployment hash
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#342 Configure router for IPv6
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, lgtm, size/L
