Repository openshift/cluster-ingress-operator, pull requests merged in 2019-11, with the labels that each got.

#319 Refactors IngressController CRD Generation
  Makefile
  hack/update-generated-crd.sh
  hack/verify-generated-crd.sh
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#322 Increases timeout for TestTLSSecurityProfile() e2e test
  test/e2e/operator_test.go
Labels: approved, lgtm, size/XS

#321 Bug 1766851: Add migration for affinity and deployment strategy
  pkg/operator/controller/ingress/deployment.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#320 Bug 1766141: Ensures LB service finalizer is removed
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/load_balancer_service.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#315 Bug 1763605: Fixes tls security policy cipher handling
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#323 Remove pod disruption budgets
  pkg/operator/controller/ingress/poddisruptionbudget.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#324 Bug 1763639: Fixes minTLSVersion for Old profile
  pkg/operator/controller/ingress/deployment.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#314 Bug 1740374: status: Set Degraded using other status conditions
  pkg/api/v1/types.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/util/retryableerror/retryableerror.go
  pkg/util/retryableerror/retryableerror_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#263 NE-66: Integrate operator metrics with Prometheus
  manifests/00-namespace.yaml
  manifests/0000_90_ingress-operator_00_prometheusrole.yaml
  manifests/0000_90_ingress-operator_01_prometheusrolebinding.yaml
  manifests/0000_90_ingress-operator_02_servicemonitor.yaml
  manifests/01-service.yaml
  manifests/02-deployment.yaml
  manifests/image-references
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#330 Updates ensureIngressDeleted() to check for removal of deps
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
Labels: approved, lgtm, size/M
