Repository openshift/cluster-ingress-operator, pull requests merged in 2020-02, with the labels that each got.

#352 [release-4.3] Bug 1789124: Configure router for IPv6
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#357 Bug 1801410: Set affinity for "NodePortService"
  pkg/operator/controller/ingress/deployment.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#359 Bug 1801543: Update CRDs
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#362 Bug 1800338: [release-4.3] update to setDefaultPublishingStrategy() to add IBMCloudPlatform
  pkg/operator/controller/ingress/controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/XS

#363 Tune AWS load balancers to be consistent with other platforms
  pkg/operator/controller/ingress/load_balancer_service.go
Labels: approved, lgtm, size/XS
