Repository openshift/cluster-ingress-operator, pull requests merged in 2020-10, with the labels that each got.

#465 Bug 1881155: Improve status reporting when pods cannot be scheduled
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/controller/status/controller.go
  pkg/util/sort.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#474 TestForwardedHeaderPolicy*: Make case-insensitive
  test/e2e/forwarded_header_policy_test.go
Labels: approved, lgtm

#471 Updating ose-cluster-ingress-operator builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#477 NE-425: Add hello openshift to CI
  manifests/image-references
  pkg/manifests/bindata.go
Labels: approved, lgtm

#406 Add run-local steps to hacking doc
  HACKING.md
Labels: approved, lgtm

#478 add current profile annotations to CVO manifests
  manifests/00-cluster-role.yaml
  manifests/00-ingress-credentials-request.yaml
  manifests/00-namespace.yaml
  manifests/0000_90_ingress-operator_00_prometheusrole.yaml
  manifests/0000_90_ingress-operator_01_prometheusrolebinding.yaml
  manifests/0000_90_ingress-operator_02_servicemonitor.yaml
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  manifests/01-cluster-role-binding.yaml
  manifests/01-role-binding.yaml
  manifests/01-role.yaml
  manifests/01-service-account.yaml
  manifests/01-service.yaml
  manifests/01-trusted-ca-configmap.yaml
  manifests/02-deployment.yaml
  manifests/03-cluster-operator.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#418 Fix up ingress controller deployment godocs
  pkg/operator/controller/ingress/deployment.go
Labels: approved, lgtm

#472 Bug 1891625: Support changing ingresscontroller load balancer scope
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
