Repository openshift/cluster-ingress-operator, pull requests merged in 2020-07, with the labels that each got.

#422 Bug 1853711: Invert http/2 kill switch logic
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/http2_disable_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#424 Bug 1854195: Invert http/2 kill switch logic
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/http2_disable_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#413 Update OWNERS
  OWNERS
Labels: approved, lgtm

#407 Bug 1842742: nodePortServiceChanged: Fix for session affinity
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#411 Update go.mod for controller-tools & controller-runtime
  go.mod
  go.sum
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/kube_helpers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, lgtm

#425 Bug 1854383: dns: Reread cloud credentials secret if it changes
  pkg/operator/controller/dns/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#420 Bug 1830271: status: Replace "DeploymentDegraded" condition
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#426 Extend router cluster-role for endpointslices
  assets/router/cluster-role.yaml
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#403 support other Azure cloud environments
  go.mod
  go.sum
  pkg/dns/azure/client/auth.go
  pkg/dns/azure/client/client.go
  pkg/dns/azure/dns.go
  pkg/operator/controller/dns/controller.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/modules.txt
Labels: approved, lgtm

#416 Adds Support for AWS Custom Endpoints
  pkg/dns/aws/dns.go
  pkg/operator/controller/dns/controller.go
  pkg/util/network.go
  pkg/util/network_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm

#430 Bumps deps for openshift/api
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/modules.txt
Labels: approved, lgtm

#431 Omit ELB EP in TestIngressControllerCustomEndpoints
  test/e2e/operator_test.go
Labels: approved, lgtm

#409 Implement HTTP header/cookie capture APIs
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm

#410 Implement HTTP Forwarded header policy API
  Makefile
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/forwarded_header_policy_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm

#432 Implement HTTP Unique-Id header API
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, lgtm
