Repository openshift/cluster-ingress-operator, pull requests merged in 2020-03, with the labels that each got.

#366 Router should deploy with a very long grace period
  pkg/operator/controller/ingress/deployment.go
Labels: approved, lgtm, size/XS

#361 Add support for AWS China region route53 Service
  pkg/dns/aws/dns.go
Labels: approved, lgtm, size/S

#365 Delete cluster DNS config from DNS provider config
  cmd/ingress-operator/start.go
  pkg/dns/aws/dns.go
  pkg/dns/azure/dns.go
Labels: approved, lgtm, size/XS

#381 Updates Docs
  HACKING.md
Labels: approved, lgtm

#376 Delete pod disruption budget logic
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/poddisruptionbudget.go
  pkg/operator/controller/names.go
  test/e2e/operator_test.go
Labels: approved, lgtm

#373 Delete iksLBProxyRegionAnnotations, rename iksLBProxyProtocolAnnotations
  pkg/operator/controller/ingress/load_balancer_service.go
Labels: approved, lgtm, size/XS

#375 Revert "Add migration for affinity and deployment strategy"
  pkg/operator/controller/ingress/deployment.go
Labels: approved, lgtm

#351 Convert more operator configuration to CLI options
  cmd/ingress-operator/start.go
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M
