Repository openshift/cluster-ingress-operator, pull requests merged in 2020-11, with the labels that each got.

#481 Bug 1892338: Fix HAProxyReloadFail alert
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#489 addowner-candita
  OWNERS
Labels: approved, lgtm, ok-to-test

#490 Bug 1896923: Configure operator metrics handler to use localhost
  cmd/ingress-operator/start.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#476 NE-199 Phase 1: Add initial Canary Controller and Canary Resources
  HACKING.md
  assets/canary/daemonset.yaml
  assets/canary/namespace.yaml
  assets/canary/route.yaml
  assets/canary/service.yaml
  cmd/ingress-operator/start.go
  hack/run-local.sh
  hack/uninstall.sh
  manifests/00-cluster-role.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/operator/config/config.go
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/controller_test.go
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace.go
  pkg/operator/controller/canary/route.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/canary/service.go
  pkg/operator/controller/canary/service_test.go
  pkg/operator/controller/names.go
  pkg/operator/controller/status/controller.go
  pkg/operator/operator.go
Labels: approved, lgtm

#491 Bug 1877693: dnsrecords specify recordTTL as 30 but the value is nul…
  go.mod
  go.sum
  manifests/00-custom-resource-definition-internal.yaml
  pkg/dns/aws/dns.go
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatoringress/v1/0000_50_dns-record.yaml
  vendor/github.com/openshift/api/operatoringress/v1/types.go
  vendor/github.com/openshift/api/operatoringress/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#485 aws: use shared credentials file instead of static only
  go.mod
  manifests/02-deployment.yaml
  pkg/dns/aws/dns.go
  pkg/manifests/bindata.go
  pkg/operator/controller/dns/controller.go
  pkg/util/aws/shared_credentials_file.go
  pkg/util/aws/shared_credentials_file_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: approved, lgtm

#484 dns: Don't hotloop on updates to DNSRecord status
  pkg/operator/controller/dns/controller.go
Labels: approved, lgtm

#494 Add IBM Cloud managed annotations to CVO manifests
  manifests/00-cluster-role.yaml
  manifests/00-custom-resource-definition-internal.yaml
  manifests/00-custom-resource-definition.yaml
  manifests/00-ingress-credentials-request.yaml
  manifests/00-namespace.yaml
  manifests/0000_90_ingress-operator_00_prometheusrole.yaml
  manifests/0000_90_ingress-operator_01_prometheusrolebinding.yaml
  manifests/0000_90_ingress-operator_02_servicemonitor.yaml
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  manifests/01-cluster-role-binding.yaml
  manifests/01-role-binding.yaml
  manifests/01-role.yaml
  manifests/01-service-account.yaml
  manifests/01-service.yaml
  manifests/01-trusted-ca-configmap.yaml
  manifests/02-deployment.yaml
  manifests/03-cluster-operator.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#492 Bug 1880902: automatically set the dnsPolicy with ClusterFirstWithHostNet when endpoint publishing strategy type is set to hostnetwork
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
