Repository openshift/cluster-ingress-operator, pull requests merged in 2020-09, with the labels that each got.

#448 Bug 1872841: Allow operator to update cluster roles
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#454 Bug 1866299: Fixes Route53 Client Handling of GovCloud Partition
  pkg/dns/aws/dns.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#415 Bug 1828618: Improve e2e test polling loops
  test/e2e/certificate_publisher_test.go
  test/e2e/forwarded_header_policy_test.go
  test/e2e/http2_disable_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#455 Bug 1866299: Fixes AWS Tagging Client for GovCloud East Region
  pkg/dns/aws/dns.go
  pkg/dns/aws/dns_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#443 [release-4.5] Bug 1868257: dns: Reread cloud credentials secret if it changes
  cmd/ingress-operator/start.go
  manifests/00-cluster-role.yaml
  pkg/dns/aws/dns.go
  pkg/dns/azure/dns.go
  pkg/manifests/bindata.go
  pkg/operator/controller/dns/controller.go
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#456 [release-4.5] Bug 1878148: Backport: Delete Router Deployment Only Upon DNSRecord Deletion
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/dns.go
  pkg/operator/controller/ingress/dns_test.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/monitoring.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/poddisruptionbudget.go
  pkg/operator/controller/ingress/rsyslog_configmap.go
  pkg/operator/controller/ingress/serviceca_configmap.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#457 Bug 1866299: Refactors AWS Provider Validation
  pkg/dns/aws/dns.go
  pkg/dns/aws/dns_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#463 Bug 1880103: go.mod: Bump library-go to remove expired dep
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#460 Bug 1866299: Forces Tagging Client to us-gov-west-1 Region
  pkg/dns/aws/dns.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#461 [Release 4.5] Bug 1880315: Fix bug in reflector not recovering from "Too large resource version"
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
