Repository openshift/cluster-ingress-operator, pull requests merged in 2020-12, with the labels that each got.

#499 hack: verify-generated-crd.sh should fail on diffs
  hack/verify-generated-crd.sh
Labels: approved, lgtm

#493 NE-199 Phase 2: Add periodic canary route HTTP checks w/ metrics & basic status reporting
  cmd/ingress-operator/start.go
  go.mod
  go.sum
  manifests/02-deployment.yaml
  manifests/image-references
  pkg/manifests/bindata.go
  pkg/operator/config/config.go
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/controller_test.go
  pkg/operator/controller/canary/http.go
  pkg/operator/controller/canary/metrics.go
  pkg/operator/controller/canary/route.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/operator.go
  test/e2e/canary_test.go
  test/e2e/operator_test.go
  vendor/github.com/tcnksm/go-httpstat/.travis.yml
  vendor/github.com/tcnksm/go-httpstat/LICENSE
  vendor/github.com/tcnksm/go-httpstat/Makefile
  vendor/github.com/tcnksm/go-httpstat/README.md
  vendor/github.com/tcnksm/go-httpstat/go18.go
  vendor/github.com/tcnksm/go-httpstat/httpstat.go
  vendor/github.com/tcnksm/go-httpstat/pre_go18.go
  vendor/modules.txt
Labels: approved, lgtm

#495 Bug 1870373: Ingress Operator reports available when DNS fails to provision
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#496 Implement HTTP header case adjustment API
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/http_header_name_case_adjustment_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#502 Bug 1904582: Assume ingresscontroller is external absent status
  pkg/operator/controller/ingress/load_balancer_service.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#501 Bug 1903165: NE-199 Follow Up Fixes.
  cmd/ingress-operator/start.go
  pkg/manifests/manifests.go
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/dns/controller.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/monitoring.go
  pkg/operator/controller/names.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/operator.go
  test/e2e/canary_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#509 Bug 1906032: Canary: Set daemonset MaxUnavailable to 10%
  assets/canary/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#507 Bug 1905490: Revert "Support changing ingresscontroller load balancer scope"
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#514 Bug 1906560: Revert "Support changing ingresscontroller load balancer scope"
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#518 Bug 1908758: Update AWS LB health check interval annotation
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#512 Bug 1906508: test/e2e: Don't clobber err in TestHeaderNameCaseAdjust
  test/e2e/http_header_name_case_adjustment_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#505 Bug 1887441: Conditionally delete generated default cert
  pkg/operator/controller/certificate-publisher/publish_certs.go
  pkg/operator/controller/certificate/default_cert.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
