Repository openshift/cluster-ingress-operator, pull requests merged in 2020-08, with the labels that each got.

#434 Follow-Up fixes for PR 427
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
Labels: approved, lgtm

#436 Bug 1862892: Reconcile openshift-ingress-router clusterrole on upgrades
  pkg/operator/controller/ingress/cluster-role.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/namespace.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#438 Bug 1866575: Escape unique-id format
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/forwarded_header_policy_test.go
  test/e2e/operator_test.go
  test/e2e/util.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#397 Bug 1861455: Add basic HAProxy alert rules for HAProxy status and Reload failures
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#437 Bug 1866568: Removes RestMapper since DynamicRestMapper is now the pkg default
  pkg/operator/operator.go
  pkg/util/restmapper.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#439 Bug 1869387: Adds CNAME support to AWS DNS
  pkg/dns/aws/dns.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#433 Fixes Bug 1866299: Adds region verification for custom endpoints
  pkg/dns/aws/dns.go
  pkg/operator/controller/dns/controller.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#442 Bug 1827364: Bumps deps and ingresscontroller CRD for h2 alpn docs
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#441 Bug 1866299: Adds support for GovCloud endpoints
  pkg/dns/aws/dns.go
  pkg/dns/aws/dns_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#445 Bug 1872058: Fixes IBM Cloud LB Annotations
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#446 Bug 1873728: publishRecordToZones: Fix status merge
  pkg/operator/controller/dns/controller.go
  pkg/operator/controller/dns/controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
