Repository openshift/cluster-ingress-operator, pull requests merged in 2021-11, with the labels that each got.

#672 Bug 2014710: test/e2e: updateDNSConfig: Replace integer literals
  test/e2e/dns_ingressdegrade_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#673 [release-4.9] Bug 2014711: Fix for Azure dns privateZone degrade e2e test
  test/e2e/dns_ingressdegrade_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#678 Update dns controller with Power VS platform
  manifests/00-ingress-credentials-request.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/dns/controller.go
Labels: lgtm, approved
