Repository openshift/cluster-ingress-operator, pull requests merged in 2021-03, with the labels that each got.

#558 [release-4.7] Bug 1932649: Canary: Add edge termination to canary route
  assets/canary/route.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/http.go
  test/e2e/canary_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#560 Bug 1933102: Canary: Schedule canary server pods to worker and infra nodes
  assets/canary/daemonset.yaml
  assets/canary/namespace.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace.go
  pkg/operator/controller/canary/namespace_test.go
  vendor/github.com/openshift/api/project/v1/doc.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/legacy.go
  vendor/github.com/openshift/api/project/v1/register.go
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#562 Bug 1934773: Canary: Perform canary test probes over https
  pkg/operator/controller/canary/http.go
  pkg/operator/controller/canary/route.go
  pkg/operator/controller/canary/route_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#565 Bug 1935528: Canary: Use cluster-wide proxy for canary client
  pkg/operator/controller/canary/http.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#550 NE-518 GCP: Implement GCP Internal LB Global Access option
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#567 Bug 1936030: Fix spurious reconciliation of NodePort services
  pkg/operator/controller/canary/route.go
  pkg/operator/controller/ingress/cluster-role.go
  pkg/operator/controller/ingress/dns.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/monitoring.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  pkg/operator/controller/ingress/poddisruptionbudget.go
  pkg/operator/controller/ingress/rsyslog_configmap.go
  pkg/operator/controller/ingress/serviceca_configmap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#547 Bug 1927364: Verify that Serivce resources have idle annotations from corresponding Endpoint resources, should they exist.
  cmd/ingress-operator/start.go
  vendor/github.com/openshift/api/unidling/v1alpha1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#564 Bug 1934904: Canary: Schedule canary server pods to worker and infra nodes
  assets/canary/daemonset.yaml
  assets/canary/namespace.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace.go
  pkg/operator/controller/canary/namespace_test.go
  vendor/github.com/openshift/api/project/v1/doc.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/legacy.go
  vendor/github.com/openshift/api/project/v1/register.go
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#572 Use HAProxy log level "info" to enable access logs
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, lgtm

#561 NE 484: Use ingress-operator subcommand instead of hello-openshift
  assets/canary/daemonset.yaml
  cmd/ingress-operator/main.go
  cmd/ingress-operator/serve-healthcheck.go
  cmd/ingress-operator/start.go
  manifests/02-deployment.yaml
  manifests/image-references
  pkg/manifests/bindata.go
  pkg/operator/config/config.go
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/http.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/operator.go
  test/e2e/canary_test.go
Labels: approved, lgtm

#575 Bug 1928931: Update DNSRecord CRD from v1beta1 to v1
  go.mod
  go.sum
  manifests/00-custom-resource-definition-internal.yaml
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatoringress/v1/0000_50_dns-record.yaml
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#541 [release-4.6] Bug 1921193: Fix inconsistent ingress operator status after upgrade
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#543 Bug 1907315: Change AWS interal LB annotation to match documentation
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#576 NE-354: Implement Tunable router header buffers
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/http_header_buffer_test.go
Labels: approved, lgtm

#487 [release-4.5] Bug 1896168: Back port HAProxy reload failures alert fix
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#548 Add service account names to credentials request manifest
  manifests/00-ingress-credentials-request.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#581 NE-553: Implement the PROXY protocol API
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm
