Repository openshift/cluster-ingress-operator, pull requests merged in 2021-09, with the labels that each got.

#648 tlsVersion13Ciphers: Delete duplicates
  pkg/operator/controller/ingress/controller.go
Labels: lgtm, approved

#652 Bug 2001479: Fix IBM Cloud DNS bugs
  pkg/dns/ibm/client/client.go
  pkg/dns/ibm/client/fake_client.go
  pkg/dns/ibm/dns.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#651 [release-4.8] Bug 2000414: Configure router to use "source" for passthrough
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved
