Repository openshift/cluster-ingress-operator, pull requests merged in 2021-04, with the labels that each got.

#586 Add the new NetworkPolicy-matching label to the namespace
  assets/router/namespace.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#585 Add http/2 and gRPC test server code as new subcommands
  cmd/ingress-operator/main.go
  go.mod
  test/grpc/server.go
  test/http/serve-healthcheck.go
  test/http2/server.go
  vendor/google.golang.org/grpc/interop/grpc_testing/test.pb.go
  vendor/google.golang.org/grpc/interop/grpc_testing/test.proto
  vendor/google.golang.org/grpc/interop/interop_test.sh
  vendor/google.golang.org/grpc/interop/test_utils.go
  vendor/modules.txt
Labels: approved, lgtm

#583 Bug 1943845: Add startup probe to the router deployment
  assets/router/deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#574 ingressclass: New controller.
  go.mod
  go.sum
  manifests/00-cluster-role.yaml
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingressclass/controller.go
  pkg/operator/controller/ingressclass/ingressclass.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#592 Bug 1946788: ingressclass: Don't set default annotation
  pkg/operator/controller/ingressclass/ingressclass.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#593 configurable_route_test: Preserve ingress spec
  test/e2e/configurable_route_test.go
Labels: approved, lgtm

#580 NE-302: Add field for configuring number of HAProxy threads in router
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/nbthread_test.go
  test/e2e/util.go
Labels: approved, lgtm

#595 Add management workload annotations
  assets/canary/daemonset.yaml
  assets/canary/namespace.yaml
  assets/router/deployment.yaml
  assets/router/namespace.yaml
  manifests/00-namespace.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, lgtm

#598 Bug 1948626: test/e2e: Make `TestRouteAdmissionPolicy` deterministic.
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#587 Bug 1948716: IBM cloud managed profile patch
  .gitignore
  Makefile
  go.mod
  go.sum
  manifests/02-deployment-ibm-cloud-managed.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
  profile-patches/ibm-cloud-managed/02-deployment.yaml-patch
  tools/tools.go
  vendor/github.com/openshift/build-machinery-go/LICENSE
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#537 Bug 1919151: Azure: Log when using domain not in zone
  pkg/dns/azure/dns.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#599 Bug 1949880: ingress: Propagate GCP ProviderParameters to Status
  pkg/operator/controller/ingress/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#600 Bug 1949435: ingressclass: Fix API group name in watch predicate
  pkg/operator/controller/ingressclass/controller.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#602 Bug 1947498: policy v1 beta1 PodDisruptionBudget is deprecated
  pkg/operator/controller/ingress/poddisruptionbudget.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#597 Bug 1941592: Alerts: Fix up HAProxyDown Alert Message
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#578 Bug 1950284: Annotate services of type LoadBalancer with user tags (AWS only)
  go.mod
  go.sum
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/install.go
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_deprecatedapirequests.yaml
  vendor/github.com/openshift/api/apiserver/v1/doc.go
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_deprecatedapirequest.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/cloudnetwork/OWNERS
  vendor/github.com/openshift/api/cloudnetwork/install.go
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
  vendor/github.com/openshift/api/cloudnetwork/v1/doc.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.pb.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.proto
  vendor/github.com/openshift/api/cloudnetwork/v1/register.go
  vendor/github.com/openshift/api/cloudnetwork/v1/types.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/cloudnetwork/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#605 Bug 1950978: ingressclass: Handle ingresscontroller deletion
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingressclass/controller.go
  pkg/operator/controller/ingressclass/ingressclass.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#604 Bug 1950270: go.mod: Update openshift/api & go version
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#603 Rename workload annotations
  assets/canary/daemonset.yaml
  assets/router/deployment.yaml
  manifests/02-deployment-ibm-cloud-managed.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
Labels: approved, bugzilla/valid-bug, lgtm

#606 [release-4.7] Bug 1954097: Annotate services of type LoadBalancer with user tags (AWS only)
  go.mod
  go.sum
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
