Repository openshift/cluster-ingress-operator, pull requests merged in 2021-12, with the labels that each got.

#684 TestIngressControllerScale: Use a private ingresscontroller
  test/e2e/operator_test.go
Labels: lgtm, approved

#687 Drop build-machinery-go for patching manifests
  Makefile
  go.mod
  go.sum
  hack/update-profile-manifests.sh
  hack/verify-profile-manifests.sh
  manifests/02-deployment-ibm-cloud-managed.yaml
  pkg/manifests/bindata.go
  profile-patches/ibm-cloud-managed/02-deployment.yaml.patch
  tools/tools.go
  vendor/github.com/openshift/build-machinery-go/LICENSE
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: lgtm, approved

#686 Bug 2032566: Azure: Add Support for Azure Stack Hub
  pkg/dns/azure/client/auth.go
  pkg/dns/azure/client/client.go
  pkg/dns/azure/dns.go
  pkg/operator/controller/dns/controller.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/2018-03-01/dns/mgmt/dns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2016-04-01/dns/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2016-04-01/dns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2016-04-01/dns/recordsets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2016-04-01/dns/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2016-04-01/dns/zones.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#582 NE-621: Support changing ingresscontroller load balancer scope
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, lifecycle/rotten

#683 Code improvements and unit tests for Alibaba DNS
  pkg/dns/alibaba/dns.go
  pkg/dns/alibaba/dns_test.go
  pkg/dns/alibaba/service.go
  pkg/dns/alibaba/util/credentials.go
  pkg/dns/alibaba/util/numbers.go
  pkg/dns/alibaba/util/numbers_test.go
  pkg/operator/controller/dns/controller.go
Labels: lgtm, approved, ok-to-test

#689 Fix update retry logic in TestConfigurableRoute*
  test/e2e/configurable_route_test.go
Labels: lgtm, approved

#681 Bug 1997226: Fix enabling PROXY protocol on an upgraded cluster
  pkg/operator/controller/ingress/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#691 Bug 1997226: setDefaultPublishingStrategy: Deep copy, tests
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
