Repository openshift/cluster-ingress-operator, pull requests merged in 2021-08, with the labels that each got.

#639 Bug 1986228: NE-310 E2E test for HSTS
  go.mod
  pkg/manifests/manifests.go
  test/e2e/hsts_policy_test.go
  test/e2e/operator_test.go
  test/e2e/util.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#641 Bug 1942657: Ingress operator stays degraded after privateZone fixed in DNS
  OWNERS
  pkg/operator/controller/dns/controller.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  test/e2e/dns_ingressdegrade_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#640 Bug 1972977: cleanup condition metrics for deleted ingress controllers
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/metrics.go
  pkg/operator/controller/ingress/metrics_test.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#643 Bug 1989005: Validate spec.clientTLS.allowedSubjectPatterns[*]
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#644 Bug 1986575: Add e2e test cases for haproxy timeout api fields, and reject negative timeout values
  pkg/operator/controller/ingress/deployment.go
  test/e2e/haproxy_timeouts_test.go
  test/e2e/util.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#650 Bug 1997407: Configure router to use "source" for passthrough
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved
