Repository openshift/cluster-ingress-operator, pull requests merged in 2021-02, with the labels that each got.

#519 NE-508 Support cluster HA mode
  go.mod
  go.sum
  pkg/operator/operator.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#513 Add rfredette to OWNERS
  OWNERS
Labels: approved, lgtm

#542 Bug 1925245: Verify that Serivce resources have idle annotations from corresponding Endpoint resources, should they exist.
  cmd/ingress-operator/start.go
  vendor/github.com/openshift/api/unidling/v1alpha1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#486 [release-4.6] Bug 1896167: Back port HAProxy reload failures alert fix
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#549 Bug 1914127: Delete the ingress.openshift.io/operator finalizer
  pkg/operator/controller/ingress/load_balancer_service.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#556 Bug 1932401: Canary: Add edge termination to canary route
  assets/canary/route.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/http.go
  test/e2e/canary_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, qe-approved
