Repository openshift/cluster-ingress-operator, pull requests merged in 2021-06, with the labels that each got.

#610 Bug 1901648: Canonical router hostname not correct
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, qe-approved

#466 Bug 1881210: desiredNodePortService: Add port 1936
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#621 Bug 1955822: Ingress: Mount router stats secret as a volume
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#622 Bug 1960284: Set the "local-with-fallback" service annotation
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#623 Bug 1935058: Set AWS session region
  go.mod
  go.sum
  pkg/dns/aws/dns.go
  vendor/github.com/aws/aws-sdk-go/aws/client/client.go
  vendor/github.com/aws/aws-sdk-go/aws/client/logger.go
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/shared_credentials_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/os.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/os_windows.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport_go1.12.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport_go1.5.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport_go1.6.go
  vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ini_parser.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/host.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restjson/restjson.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restjson/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/timestamp.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go
  vendor/github.com/aws/aws-sdk-go/service/elb/api.go
  vendor/github.com/aws/aws-sdk-go/service/elb/doc.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/doc.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/api.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/doc.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
  vendor/github.com/aws/aws-sdk-go/service/sso/api.go
  vendor/github.com/aws/aws-sdk-go/service/sso/doc.go
  vendor/github.com/aws/aws-sdk-go/service/sso/errors.go
  vendor/github.com/aws/aws-sdk-go/service/sso/service.go
  vendor/github.com/aws/aws-sdk-go/service/sso/ssoiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/aws/aws-sdk-go/service/sts/doc.go
  vendor/github.com/jmespath/go-jmespath/.travis.yml
  vendor/github.com/jmespath/go-jmespath/Makefile
  vendor/github.com/jmespath/go-jmespath/go.mod
  vendor/github.com/jmespath/go-jmespath/go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#618 Add alebedev87 to OWNERS
  OWNERS
Labels: approved, lgtm

#616 [release-4.7] Bug 1960776: Reconcile openshift-ingress namespace on upgrade
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/namespace.go
  pkg/operator/controller/ingress/namespace_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#588 Ability to Customize HAProxy 2.x Error Page
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/names.go
  pkg/operator/controller/sync-http-error-code-configmap/controller.go
  pkg/operator/controller/sync-http-error-code-configmap/controller_test.go
  pkg/operator/controller/sync-http-error-code-configmap/httperrorcode_configmap.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: approved, lgtm

#617 NE-472:Add tlsv1.3 support
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm

#627 [release-4.7] Bug 1973983: Canary: Handle downgrades from 4.8 to 4.7 properly
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/daemonset_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
