Repository openshift/cluster-ingress-operator, pull requests merged in 2022-09, with the labels that each got.

#758 [release-4.8] Bug 2084337: Fix enabling PROXY protocol on an upgraded cluster
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#826 OCPBUGS-1049: test/e2e: Fix TestCanaryRoute security context
  test/e2e/canary_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#819 Add IBM Cloud DNS support for Power VS
  manifests/00-ingress-credentials-request.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/dns/controller.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#769 Bug 2066560: Make ingress clusteroperator progressing=true when router deployment is rolling out
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#820 [release-4.10] BUG 2094051: Fix removing custom created service in openshift-ingress with same naming convention
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#790 Enable switching of AWS CLB to NLB without deletion of IngressController object.
  pkg/operator/controller/configurable-route/controller.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/load_balancer_service.go
  test/e2e/all_test.go
  test/e2e/checkinterval_test.go
  test/e2e/operator_test.go
  test/e2e/reloadinterval_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
