Repository openshift/cluster-ingress-operator, pull requests merged in 2022-06, with the labels that each got.

#756 Bug 2080379: Group all e2e tests as parallel or serial
  Makefile
  hack/verify-e2e-test-all-presence.sh
  test/e2e/all_test.go
  test/e2e/canary_test.go
  test/e2e/certificate_publisher_test.go
  test/e2e/checkinterval_test.go
  test/e2e/client_tls_test.go
  test/e2e/forwarded_header_policy_test.go
  test/e2e/haproxy_timeouts_test.go
  test/e2e/hsts_policy_test.go
  test/e2e/http_header_buffer_test.go
  test/e2e/http_header_name_case_adjustment_test.go
  test/e2e/maxconn_test.go
  test/e2e/operator_test.go
  test/e2e/router_compression_test.go
  test/e2e/util.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#737 Bug 2055601: Add cluster tag to *.apps domain record
  pkg/dns/azure/client/client.go
  pkg/dns/azure/dns.go
  pkg/operator/controller/dns/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#764 Bug 2075671: Add a e2e test that verifies the ingress operator's cache doesn't include everything
  test/e2e/all_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#713 Bug 2079517: Use externalTrafficPolicy: Cluster with OVN
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#767 Bug 2094932: MGMT-10403: Set the `defaultPlacement` for none-platform SNO clusters installed before 4.11
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#775 Bug 2094962: Fix flakey logic in haproxy timeout tests
  test/e2e/haproxy_timeouts_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#780 Bug 2095229: desiredRouterDeployment: Check for nil hostNetwork
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#785 Bug 2094932: Ingress operator needs permission to list nodes
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#783 Bug 2097555: Fix loadBalancerServiceAnnotationsChanged check and update
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#788 Bug 2094932: Patching config.ingresses status requires patch permissions
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#724 Bug 1944851: Clear route status when an ingress controller is deleted or a route is un-admitted
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/router_status.go
  pkg/operator/controller/ingress/status.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
  test/e2e/router_status_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#761 Bug 2041616: Do not create DNS records for IngressControllers with domain not matching baseDomain
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/dns.go
  pkg/operator/controller/ingress/dns_test.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  test/e2e/all_test.go
  test/e2e/domain_not_matching_base_test.go
Labels: lgtm, approved, tide/merge-method-squash, bugzilla/valid-bug, bugzilla/severity-medium

#714 Bug 2093462: status: Watch clusteroperators
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/status/controller.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, lifecycle/stale, bugzilla/valid-bug, bugzilla/severity-low

#792 Bug 2100630: Fix flakey logic in haproxy timeout tests
  test/e2e/haproxy_timeouts_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#793 Bug 2086887: Add better debug logging to TestIngressOperatorCacheIsNotGlobal to help debug flakes
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
