Repository openshift/cluster-ingress-operator, pull requests merged in 2022-08, with the labels that each got.

#818 OCPBUGS-368: Fix e2e tests for pod security violations
  test/e2e/util.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#815 DPP-10860: Update Bugzilla links to "Networking" component
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#796 NE-969: Add IBM DNS Services provider support for private clusters
  go.mod
  go.sum
  manifests/00-ingress-credentials-request.yaml
  pkg/dns/ibm/common.go
  pkg/dns/ibm/private/client/client.go
  pkg/dns/ibm/private/client/fake_client.go
  pkg/dns/ibm/private/dnssvcs_provider.go
  pkg/dns/ibm/private/dnssvcs_provider_test.go
  pkg/dns/ibm/public/cis_provider.go
  pkg/dns/ibm/public/cis_provider_test.go
  pkg/dns/ibm/public/client/client.go
  pkg/dns/ibm/public/client/fake_client.go
  pkg/manifests/bindata.go
  pkg/operator/controller/dns/controller.go
  vendor/github.com/IBM/go-sdk-core/v4/core/cp4d_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v4/core/log.go
  vendor/github.com/IBM/go-sdk-core/v4/core/unmarshal.go
  vendor/github.com/IBM/go-sdk-core/v5/LICENSE
  vendor/github.com/IBM/go-sdk-core/v5/core/authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/authenticator_factory.go
  vendor/github.com/IBM/go-sdk-core/v5/core/base_service.go
  vendor/github.com/IBM/go-sdk-core/v5/core/basic_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/bearer_token_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/config_utils.go
  vendor/github.com/IBM/go-sdk-core/v5/core/constants.go
  vendor/github.com/IBM/go-sdk-core/v5/core/container_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/cp4d_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/datetime.go
  vendor/github.com/IBM/go-sdk-core/v5/core/detailed_response.go
  vendor/github.com/IBM/go-sdk-core/v5/core/doc.go
  vendor/github.com/IBM/go-sdk-core/v5/core/file_with_metadata.go
  vendor/github.com/IBM/go-sdk-core/v5/core/gzip.go
  vendor/github.com/IBM/go-sdk-core/v5/core/iam_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/jwt_utils.go
  vendor/github.com/IBM/go-sdk-core/v5/core/log.go
  vendor/github.com/IBM/go-sdk-core/v5/core/noauth_authenticator.go
  vendor/github.com/IBM/go-sdk-core/v5/core/parameterized_url.go
  vendor/github.com/IBM/go-sdk-core/v5/core/request_builder.go
  vendor/github.com/IBM/go-sdk-core/v5/core/unmarshal_v2.go
  vendor/github.com/IBM/go-sdk-core/v5/core/utils.go
  vendor/github.com/IBM/go-sdk-core/v5/core/version.go
  vendor/github.com/IBM/go-sdk-core/v5/core/vpc_instance_authenticator.go
  vendor/github.com/IBM/networking-go-sdk/common/version.go
  vendor/github.com/IBM/networking-go-sdk/dnsrecordsv1/dns_records_v1.go
  vendor/github.com/IBM/networking-go-sdk/dnssvcsv1/dns_svcs_v1.go
  vendor/github.com/go-openapi/strfmt/bson.go
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#814 Bug 2089482: Do not use deprecated API field InfrastructureStatus.Platform
  go.mod
  pkg/operator/controller/dns/controller.go
  pkg/operator/controller/ingress/controller.go
  pkg/util/platform_status.go
  test/e2e/domain_not_matching_base_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
