Repository openshift/cluster-ingress-operator, pull requests merged in 2022-10, with the labels that each got.

#781 NE-568: Add dnsManagementPolicy option to ingresscontrollers
  pkg/operator/controller/dns/controller.go
  pkg/operator/controller/dns/controller_test.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/dns.go
  pkg/operator/controller/ingress/dns_test.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  test/e2e/all_test.go
  test/e2e/domain_not_matching_base_test.go
  test/e2e/forwarded_header_policy_test.go
  test/e2e/http_header_buffer_test.go
  test/e2e/http_header_name_case_adjustment_test.go
  test/e2e/operator_test.go
  test/e2e/unmanaged_dns_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, tide/merge-method-squash, px-approved, docs-approved, qe-approved

#830 OCPBUGS-236: Bump openshift/api for reloadInterval fix
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/reloadinterval_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  vendor/github.com/openshift/api/authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01_imagepruner.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machinehealthcheck.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_01_alertingrules.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_insights-operator_00-insightsoperator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  vendor/github.com/openshift/api/sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
  vendor/github.com/openshift/api/sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug

#833 Bug 2107462: Update CGO_ENABLED=1
  Makefile
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#839 OCPBUGS-2334: Added nil check for service object on load balancer scope change
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#842 OCPBUGS-2429: Fix TestReloadInterval min value test cases and race conditions
  test/e2e/reloadinterval_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#837 NE-975: Use ingress config to set default LB type on AWS
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/operator.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#845 OCPBUGS-2493: Fix TestUnmanagedDNSToManagedDNSInternal E2E test race conditions
  test/e2e/unmanaged_dns_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#843 OCPBUGS-2435: TestRouterCompressionOperation: Nil-pointer fix
  test/e2e/router_compression_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#795 [release-4.9] Bug 2100631: Fix flakey logic in haproxy timeout tests
  test/e2e/haproxy_timeouts_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved, backport-risk-assessed

#834 Updating ose-cluster-ingress-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile
  pkg/manifests/bindata.go
  pkg/operator/controller/certificate/controller.go
  pkg/util/aws/shared_credentials_file.go
  test/e2e/maxconn_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#836 NE-1071: Default HAProxy maxconn value to 50000 for OCP 4.12)
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1alpha1/register.go
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#823 Bug 1962502: Add alerts for unmanaged Routes and Ingresses without IngressClassName
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#824 OCPBUGS-853: certificate-publisher: Don't publish extraneous certificates
  pkg/operator/controller/certificate-publisher/controller.go
  pkg/operator/controller/certificate-publisher/publish_ca.go
  pkg/operator/controller/certificate-publisher/publish_certs.go
  pkg/operator/controller/certificate-publisher/publish_certs_test.go
  pkg/operator/controller/certificate/controller.go
  pkg/operator/controller/ingress/controller.go
  pkg/util/ingresscontroller/ingresscontroller.go
  test/e2e/all_test.go
  test/e2e/certificate_publisher_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-critical, jira/valid-bug

#828 Bug 2117524: Update CRLs when they expire
  pkg/operator/controller/crl/controller.go
  pkg/operator/controller/crl/crl_configmap.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#850 OCPBUGS-2848: Support matchExpressions selectors with route metrics
  pkg/operator/controller/route-metrics/controller.go
  test/e2e/route_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug

#808 OCPBUGS-1807: Fix bad `handleSingleNode4Dot11Upgrade` log message
  pkg/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-informational, jira/valid-bug
