Repository openshift/cluster-ingress-operator, pull requests merged in 2022-03, with the labels that each got.

#709 Bug 2058699: Upgradeable Condition in Operator and IC status
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#715 Bug 1995953: Add unit test for verifying router deployment env is always sorted
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#718 Bug 2007246: Ingress Controller does not set allowPrivilegeEscalation in the router deployment
  assets/router/deployment.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#706 [release-4.9] Bug 2057518: Normalize the AWS internal LB annotation value
  pkg/operator/controller/ingress/load_balancer_service.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#711 [release-4.9] Bug 2060111: Set Upgradeable=False if default cert has no SAN
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved, backport-risk-assessed

#721 Bug 2066444: update relatedObjects for clusteroperator status
  manifests/03-cluster-operator.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/status/controller.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#723 Bug 2021446: Set canary status as unknown if not admitted to default ingress controller
  pkg/operator/controller/canary/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#729 Bug 2069457: Delete LoadBalancer-type service finalizer logic
  pkg/manifests/manifests.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
