Repository openshift/cluster-ingress-operator, pull requests merged in 2022-05, with the labels that each got.

#753 Bug 2081447: `desiredRouterDeployment`: Fix for port defaulting
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#749 AUTH-184: manifests/deployment: comply to restricted pod security level
  manifests/02-deployment-ibm-cloud-managed.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#754 Add support for route53 in the us-isob-east-1 region + fix
  pkg/dns/aws/dns.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#703 Add support for route53 in the us-isob-east-1 region
  pkg/dns/aws/dns.go
Labels: lgtm, ok-to-test, docs-approved, qe-approved

#735 NE-577: Support a Configurable ROUTER_MAX_CONNECTIONS in HAproxy
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/maxconn_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/0000_03_marketplace-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#760 Bug 2084433: AUTH-133: assets: comply to pod security
  assets/canary/daemonset.yaml
  assets/router/namespace.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/ingress/namespace.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#727 NE-825: Update router to use random balancing algorithm once again
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#451 NE-408: Allow configuring ELB connection idle timeout
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  test/e2e/operator_test.go
  test/e2e/util.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#762 Bug 2082428: Add MicroSecond processing
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/monitoring/install.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_01_alertingrules.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/doc.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/register.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/types.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
