Repository openshift/cluster-ingress-operator, pull requests merged in 2022-04, with the labels that each got.

#734 Bug 2071139: add pod eviction permission
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#733 Bug 2072106: Fix test `Errorf` limitation in go 1.18
  pkg/dns/ibm/dns_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/nodeport_service_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#736 NE-781: Allow users to tune kubelet probe timeouts
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
  test/e2e/util.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#740 Bug 2075671: Fix k8s client cache object global inclusion and duplication.
  pkg/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#741 Revert "Bug 2007246: Ingress Controller does not set allowPrivilegeEscalation in the router deployment"
  assets/router/deployment.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#730 Add Nutanix platform
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/load_balancer_service.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#707 BUG 2054200: Fix removing custom created service in openshift-ingress with same name
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#744 BUG 2076984: test/e2e: add resilience to RBAC test teardown
  test/e2e/configurable_route_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#712 NE-585: Make ROUTER_BACKEND_CHECK_INTERVAL configurable
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/checkinterval_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#742 Bug 2076193: Remove special-casing for default ingresscontroller probe parameters
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#728 MGMT-9797: Determine number of replicas according to `DefaultPlacement`
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/replicas.go
  pkg/operator/operator.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#743 Bug 2007246: Add allowPrivilegeEscalation to the router container
  assets/router/deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#694 Specify host port for host networking strategy
  assets/router/deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#674 NE-882: Set `ROUTER_DOMAIN` to enable route subdomain field
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#745 Bug 2079468: Enhance the waitForIngressControllerCondition for better CI results
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
