Repository openshift/cluster-ingress-operator, pull requests merged in 2023-10, with the labels that each got.

#981 OCPBUGS-20192: Require non-readonly filesystem in router container
  pkg/manifests/assets/router/deployment.yaml
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#983 OCPBUGS-21803: test/e2e: Add test case for 2000000 maxConnections
  test/e2e/maxconn_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#991 [release-4.13] OCPBUGS-22402: test/e2e: Don't use openshift/origin-node
  test/e2e/client_tls_test.go
  test/e2e/hsts_policy_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#992 [release-4.12] OCPBUGS-22432: test/e2e: Don't use openshift/origin-node
  test/e2e/client_tls_test.go
  test/e2e/hsts_policy_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#993 [release-4.11] OCPBUGS-22433: test/e2e: Don't use openshift/origin-node
  test/e2e/client_tls_test.go
  test/e2e/hsts_policy_test.go
  test/e2e/util.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#948 OCPBUGS-14994: Don't add clientca-configmap finalizer if deleting
  pkg/operator/controller/clientca-configmap/controller.go
  pkg/operator/controller/clientca-configmap/controller_test.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference
