Repository openshift/cluster-ingress-operator, pull requests merged in 2023-01, with the labels that each got.

#863 OCPBUGS-4703: Replace liveness-grace-period-seconds annotation
  assets/router/deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-moderate, jira/valid-bug

#866 OCPBUGS-4759: Do not manage DNS for an ingresscontroller with domain mismatch in GCP
  pkg/operator/controller/ingress/dns.go
  pkg/operator/controller/ingress/dns_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#854 OCPBUGS-434: Absorb PodsScheduled condition into MinAvailable
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/metrics_test.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#864 OCPBUGS-4573: Target metrics port by name in internal service
  assets/router/service-internal.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#878 OCPBUGS-6700: updateIngressClass: Fix log message
  pkg/operator/controller/ingressclass/ingressclass.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-informational, jira/valid-bug, jira/valid-reference
