Repository openshift/cluster-ingress-operator, pull requests merged in 2023-09, with the labels that each got.

#871 OCPBUGS-3356: E2E test for cookie length truncation
  test/e2e/all_test.go
  test/e2e/client_tls_test.go
  test/e2e/tuning_options_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#973 OCPBUGS-15900: TestMTLSWithCRLs: only try to parse HTTP status code from curl output when stdout is long enough.
  test/e2e/client_tls_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#975 OCPBUGS-18248: Prevent GatewayClass from getting recreated
  pkg/operator/controller/gatewayclass/servicemeshcontrolplane.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#869 OCPBUGS-3541: Don't create route metrics for ingress controllers that are not admitted
  pkg/operator/controller/route-metrics/controller.go
  pkg/operator/controller/route-metrics/controller_test.go
  test/unit/util.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference
