Repository openshift/cluster-ingress-operator, pull requests merged in 2023-08, with the labels that each got.

#968 OCPBUGS-12790: README: Fix Bugzilla link
  README.md
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#929 NE-1244: Use permissions instead of the "Contributor" role in Azure CredentialsRequest
  manifests/00-ingress-credentials-request.yaml
Labels: lgtm, approved, jira/valid-reference

#934 OCPBUGS-10875: gateway-service-dns: Set DNS policy appropriately
  pkg/operator/controller/gateway-service-dns/controller.go
  pkg/operator/controller/gateway-service-dns/controller_test.go
  pkg/resources/dnsrecord/dns.go
  pkg/resources/dnsrecord/dns_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#947 OCPBUGS-14995: desiredRouterDeployment: Set HostPort if needed
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#966 [release-4.13] NE-1341: Add support for AWS shared VPC in another account
  go.mod
  go.sum
  manifests/00-ingress-credentials-request.yaml
  pkg/dns/aws/dns.go
  pkg/dns/split/dns.go
  pkg/dns/split/dns_test.go
  pkg/manifests/bindata.go
  pkg/operator/controller/dns/controller.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#954 [release-4.12] OCPBUGS-15467: Add missing AWS permission for ListTagsForResources
  manifests/00-ingress-credentials-request.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#922 [release-4.12] OCPBUGS-13049: bump controller-runtime to fix the multi namespace cache indexing
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#965 OCPBUGS-16089: Set spec.subdomain on the canary route
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/http.go
  pkg/operator/controller/canary/route.go
  pkg/operator/controller/canary/route_test.go
  test/e2e/canary_test.go
  test/e2e/client_tls_test.go
  test/e2e/operator_test.go
  test/e2e/router_compression_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#970 OCPBUGS-17359: test/e2e: Don't use openshift/origin-node
  test/e2e/client_tls_test.go
  test/e2e/hsts_policy_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#972 OCPBUGS-17733: [release-4.13] remove shared VPC cred request
  manifests/00-ingress-credentials-request.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#967 OCPBUGS-15978: Check public DNS zone when reporting status
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
