Repository openshift/cluster-ingress-operator, pull requests merged in 2023-02, with the labels that each got.

#877 OCPBUGS-6698: Fix conflict error message in ensureNodePortService
  pkg/operator/controller/ingress/nodeport_service.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-informational, jira/valid-bug, jira/valid-reference

#879 OCPBUGS-6701: Avoid spurious updates for scope in IngressClass
  pkg/operator/controller/ingressclass/ingressclass.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#868 OCPBUGS-4827: Add missing AWS permission for ListTagsForResources
  manifests/00-ingress-credentials-request.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#874 CFE-679: Add user defined tags to the created DNS resources
  go.mod
  go.sum
  pkg/dns/azure/client/client.go
  pkg/dns/azure/client/fake_client.go
  pkg/dns/azure/dns.go
  pkg/dns/azure/dns_test.go
  pkg/operator/controller/dns/controller.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
