Repository openshift/cluster-ingress-operator, pull requests merged in 2023-07, with the labels that each got.

#958 OCPBUGS-15434: [release-4.13] Fix invalid DNS name formatting for GCP
  pkg/operator/controller/gateway-service-dns/controller.go
  pkg/operator/controller/gateway-service-dns/controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#931 OCPBUGS-7546: Allow only 1 disruption with 3 replicas
  pkg/operator/controller/ingress/poddisruptionbudget.go
  pkg/operator/controller/ingress/poddisruptionbudget_test.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#932 OCPBUGS-9274: canary: Tolerate infra node NoExecute taint
  assets/canary/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/daemonset_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#900 RFE-3765 - Allow Ingress to Modify the HAProxy Log Length when using a Sidecar
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/rsyslog_configmap.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#905 NE-1269: Replace bindata using embed
  .gitignore
  Makefile
  go.mod
  go.sum
  hack/update-generated-bindata.sh
  hack/verify-generated-bindata.sh
  pkg/manifests/assets/canary/daemonset.yaml
  pkg/manifests/assets/canary/namespace.yaml
  pkg/manifests/assets/canary/route.yaml
  pkg/manifests/assets/canary/service.yaml
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_gatewayclasses.yaml
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_gateways.yaml
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_httproutes.yaml
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_referencegrants.yaml
  pkg/manifests/assets/router/cluster-role-binding.yaml
  pkg/manifests/assets/router/cluster-role.yaml
  pkg/manifests/assets/router/deployment.yaml
  pkg/manifests/assets/router/metrics/cluster-role-binding.yaml
  pkg/manifests/assets/router/metrics/cluster-role.yaml
  pkg/manifests/assets/router/metrics/role-binding.yaml
  pkg/manifests/assets/router/metrics/role.yaml
  pkg/manifests/assets/router/namespace.yaml
  pkg/manifests/assets/router/service-account.yaml
  pkg/manifests/assets/router/service-cloud.yaml
  pkg/manifests/assets/router/service-internal.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  tools/tools.go
  vendor/github.com/kevinburke/go-bindata/.gitignore
  vendor/github.com/kevinburke/go-bindata/.mailmap
  vendor/github.com/kevinburke/go-bindata/.travis.yml
  vendor/github.com/kevinburke/go-bindata/AUTHORS.txt
  vendor/github.com/kevinburke/go-bindata/CONTRIBUTING.md
  vendor/github.com/kevinburke/go-bindata/LICENSE
  vendor/github.com/kevinburke/go-bindata/Makefile
  vendor/github.com/kevinburke/go-bindata/README.md
  vendor/github.com/kevinburke/go-bindata/asset.go
  vendor/github.com/kevinburke/go-bindata/bits.go
  vendor/github.com/kevinburke/go-bindata/bytewriter.go
  vendor/github.com/kevinburke/go-bindata/config.go
  vendor/github.com/kevinburke/go-bindata/convert.go
  vendor/github.com/kevinburke/go-bindata/debug.go
  vendor/github.com/kevinburke/go-bindata/doc.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/main.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/version.go
  vendor/github.com/kevinburke/go-bindata/release.go
  vendor/github.com/kevinburke/go-bindata/restore.go
  vendor/github.com/kevinburke/go-bindata/safefile.go
  vendor/github.com/kevinburke/go-bindata/stringwriter.go
  vendor/github.com/kevinburke/go-bindata/toc.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#880 NE-1183: Rename unit tests for specific functions
  pkg/dns/alibaba/dns_test.go
  pkg/dns/alibaba/util/numbers_test.go
  pkg/dns/aws/dns_test.go
  pkg/dns/azure/dns_test.go
  pkg/dns/gcp/provider_test.go
  pkg/dns/ibm/private/dnssvcs_provider_test.go
  pkg/dns/ibm/public/cis_provider_test.go
  pkg/operator/controller/canary/controller_test.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace_test.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/canary/service_test.go
  pkg/operator/controller/certificate-publisher/publish_certs_test.go
  pkg/operator/controller/certificate/default_cert_test.go
  pkg/operator/controller/dns/controller_test.go
  pkg/operator/controller/ingress/controller_test.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/metrics_test.go
  pkg/operator/controller/ingress/monitoring_test.go
  pkg/operator/controller/ingress/namespace_test.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  pkg/operator/controller/ingress/poddisruptionbudget_test.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/controller/sync-http-error-code-configmap/controller_test.go
  pkg/resources/dnsrecord/dns_test.go
  pkg/util/aws/shared_credentials_file_test.go
  pkg/util/hash_test.go
  pkg/util/network_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#886 NE-1189: Refactor Test_desiredLoadBalancerService
  pkg/operator/controller/ingress/load_balancer_service_test.go
Labels: lgtm, approved, jira/valid-reference

#887 RFE-3007: Expose option-contstats as an unsupported option
  pkg/operator/controller/ingress/deployment.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference
