Repository openshift/cluster-ingress-operator, pull requests merged in 2023-06, with the labels that each got.

#939 OCPBUGS-6661, OCPBUGS-9464: Move mTLS CRL handling into the router, and fix accidental duplication of CRLs
  go.mod
  go.sum
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/crl/crl_configmap.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/all_test.go
  test/e2e/client_tls_test.go
  test/e2e/util_certgen.go
  test/e2e/util_test.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/operator-framework/api/LICENSE
  vendor/github.com/operator-framework/api/pkg/lib/version/version.go
  vendor/github.com/operator-framework/api/pkg/operators/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/register.go
  vendor/github.com/operator-framework/api/pkg/operators/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#941 [release-4.12] OCPBUGS-14454, OCPBUGS-14455: Handle mTLS CRLs, and fix accidental CRL duplication
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/crl/crl_configmap.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/all_test.go
  test/e2e/client_tls_test.go
  test/e2e/util_certgen.go
  test/e2e/util_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#942 [release-4.11] OCPBUGS-14456, OCPBUGS-14457: Handle mTLS CRLs, and fix accidental CRL duplication
  manifests/00-cluster-role.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/crl/crl_configmap.go
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/all_test.go
  test/e2e/client_tls_test.go
  test/e2e/util.go
  test/e2e/util_certgen.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#944 OCPBUGS-13810: Update TestAWSELBConnectionIdleTimeout to not use wildcard DNS record
  test/e2e/operator_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#927 OCPBUGS-13190: Avoid spurious updates for internalTrafficPolicy
  assets/router/service-cloud.yaml
  assets/router/service-internal.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#921 [release-4.13] OCPBUGS-12743: bump controller-runtime to fix the multi namespace cache indexing
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/lazyrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/register.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/types.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#924 OCPBUGS-13106: Add ingress controller status logging on waitForIngressControllerCondition
  test/e2e/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#949 OCPBUGS-15100: Create valid DNS names for Gateway API on GCP
  pkg/operator/controller/gateway-service-dns/controller.go
  pkg/operator/controller/gateway-service-dns/controller_test.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#951 OCPBUGS-14998: Only use RoleARN for Route53 API
  pkg/dns/aws/dns.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#946 OCPBUGS-14396: Set controller-runtime logger to a null logger for E2E
  test/e2e/operator_test.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#956 OCPBUGS-15100: Fix previous attempt of adding a missing trailing dot to hostname
  pkg/operator/controller/gateway-service-dns/controller.go
  pkg/operator/controller/gateway-service-dns/controller_test.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference
