Repository openshift/cluster-ingress-operator, pull requests merged in 2024-10, with the labels that each got.

#1116 OCPBUGS-36340: Retry IngressController and Route updates in E2E tests
  pkg/operator/controller/names.go
  test/e2e/allowed_source_ranges_test.go
  test/e2e/canary_test.go
  test/e2e/client_tls_test.go
  test/e2e/forwarded_header_policy_test.go
  test/e2e/http2_disable_test.go
  test/e2e/http_header_buffer_test.go
  test/e2e/operator_test.go
  test/e2e/route_metrics_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1137 OCPBUGS-37932: Always log AWS service endpoints
  pkg/dns/aws/dns.go
  pkg/dns/aws/dns_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1153 OCPBUGS-43033: e2e/ingress_dns: support both private & public
  test/e2e/dns_ingressdegrade_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1150 OCPBUGS-43095: Add e2e test for duplicate Transfer-Encoding headers
  cmd/ingress-operator/main.go
  test/e2e/all_test.go
  test/e2e/ocpbugs48050_test.go
  test/ocpbugs48050/server.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1154 OCPBUGS-42480: Limit SHA-1 check to the leaf cert in default cert chain
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1161 OCPBUGS-43095: Add alert for RFC 7230 violation in Transfer-Encoding headers
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
  pkg/manifests/bindata.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
