Repository openshift/cluster-ingress-operator, pull requests merged in 2024-05, with the labels that each got.

#1047 OCPBUGS-32887: Allow operator to update Route spec.subdomain
  manifests/00-cluster-role.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1018 NE-1400: Bump to OSSM 2.5 and Gateway API v0.6.2 CRDs
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_gatewayclasses.yaml
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_gateways.yaml
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_httproutes.yaml
  pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_referencegrants.yaml
  pkg/operator/controller/gatewayclass/servicemeshcontrolplane.go
Labels: lgtm, approved, jira/valid-reference

#1067 OCPBUGS-34262: Updating ose-cluster-ingress-operator-container image to be consistent with ART for 4.17
  .ci-operator.yaml
  Dockerfile
  go.mod
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#1055 OCPBUGS-33990: Avoid spurious updates for internalTrafficPolicy [Backport to 4.13]
  assets/router/service-cloud.yaml
  assets/router/service-internal.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests/00-custom-resource-definition.yaml
  pkg/manifests/manifests/00-namespace.yaml
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
