Repository openshift/cluster-ingress-operator, pull requests merged in 2024-01, with the labels that each got.

#844 CCO-249: Replace GCP role with explicit permissions
  manifests/00-ingress-credentials-request.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#980 OCPBUGS-15253: Include namespace in prometheus alerts IngressWithoutClassName and UnmanagedRoutes
  manifests/0000_90_ingress-operator_03_prometheusrules.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1015 OCPBUGS-26544: Replace GCP role with explicit permissions
  manifests/00-ingress-credentials-request.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1012 NE-1490: update to go v1.20
  go.mod
Labels: lgtm, approved, jira/valid-reference

#1019 OCPBUGS-28230: add FallbackToLogsOnError for easier debugging
  manifests/02-deployment-ibm-cloud-managed.yaml
  manifests/02-deployment.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-bug, jira/valid-reference
