Repository openshift/cluster-ingress-operator, pull requests merged in 2024-06, with the labels that each got.

#1052 OCPBUGS-23221: internalServiceChanged: Fix target port logic
  pkg/manifests/assets/router/deployment.yaml
  pkg/manifests/assets/router/service-cloud.yaml
  pkg/manifests/assets/router/service-internal.yaml
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace_test.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/gatewayapi/crds.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/monitoring_test.go
  pkg/operator/controller/ingress/namespace_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  pkg/operator/controller/ingress/poddisruptionbudget_test.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1070 [release-4.12] OCPBUGS-34757: Avoid spurious updates for internalTrafficPolicy
  assets/router/service-cloud.yaml
  assets/router/service-internal.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1073 [release-4.13] OCPBUGS-34765: Don't add clientca-configmap finalizer if deleting
  pkg/operator/controller/clientca-configmap/controller.go
  pkg/operator/controller/clientca-configmap/controller_test.go
  pkg/operator/operator.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1080 [release-4.12] OCPBUGS-35027: Don't add clientca-configmap finalizer if deleting
  go.mod
  pkg/operator/controller/clientca-configmap/controller.go
  pkg/operator/controller/clientca-configmap/controller_test.go
  pkg/operator/operator.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1081 [release-4.15] OCPBUGS-35028: internalServiceChanged: Fix target port logic
  go.mod
  go.sum
  pkg/manifests/assets/router/deployment.yaml
  pkg/manifests/assets/router/service-cloud.yaml
  pkg/manifests/assets/router/service-internal.yaml
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace_test.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/gatewayapi/crds.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/monitoring_test.go
  pkg/operator/controller/ingress/namespace_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  pkg/operator/controller/ingress/poddisruptionbudget_test.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1014 [release-4.15] OCPBUGS-28928: Prevent upgrades for SHA1 default cert and SHA1 route certs
  go.mod
  go.sum
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/controller/names.go
  pkg/operator/controller/route-metrics/controller.go
  pkg/operator/controller/route-upgradeable/controller.go
  pkg/operator/operator.go
  test/e2e/all_test.go
  test/e2e/client_tls_test.go
  test/e2e/route_upgradeable_test.go
  test/e2e/util_test.go
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
  vendor/github.com/openshift/api/cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1087 OCPBUGS-35368: Add Regexp Anchor to TestAll
  Makefile
Labels: lgtm, approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#978 OCPBUGS-9037: Change Canary to use passthrough route
  pkg/manifests/assets/canary/daemonset.yaml
  pkg/manifests/assets/canary/route.yaml
  pkg/manifests/assets/canary/service.yaml
  pkg/operator/controller/canary/controller.go
  pkg/operator/controller/canary/daemonset.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/canary/service.go
  pkg/operator/controller/canary/service_test.go
  test/e2e/all_test.go
  test/e2e/canary_test.go
  test/e2e/client_tls_test.go
  test/e2e/router_compression_test.go
  test/http/serve-healthcheck.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1086 [release-4.14] OCPBUGS-35399: Internal service changed: fix target port logic
  go.mod
  go.sum
  pkg/manifests/assets/router/deployment.yaml
  pkg/manifests/assets/router/service-cloud.yaml
  pkg/manifests/assets/router/service-internal.yaml
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace_test.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/gatewayapi/crds.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/monitoring_test.go
  pkg/operator/controller/ingress/namespace_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  pkg/operator/controller/ingress/poddisruptionbudget_test.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1085 OCPBUGS-35356: Retry IngressController updates in router status E2E
  test/e2e/router_status_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1091 NO-JIRA: addowner-Thealisyed
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1089 OCPBUGS-35453: [release-4.13] internal service changed fix target port logic
  assets/router/deployment.yaml
  assets/router/service-cloud.yaml
  assets/router/service-internal.yaml
  go.mod
  go.sum
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace_test.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/gatewayapi/crds.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/monitoring_test.go
  pkg/operator/controller/ingress/namespace_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1090 NO-JIRA: Add grzpiotrowski to OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-reference
