Repository openshift/cluster-ingress-operator, pull requests merged in 2024-07, with the labels that each got.

#1092 [release-4.12] OCPBUGS-35454: internal service changed fix target port logic
  assets/router/deployment.yaml
  assets/router/service-cloud.yaml
  assets/router/service-internal.yaml
  go.mod
  go.sum
  pkg/manifests/bindata.go
  pkg/operator/controller/canary/daemonset_test.go
  pkg/operator/controller/canary/namespace_test.go
  pkg/operator/controller/canary/route_test.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/controller/ingress/internal_service.go
  pkg/operator/controller/ingress/internal_service_test.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/monitoring_test.go
  pkg/operator/controller/ingress/namespace_test.go
  pkg/operator/controller/ingress/nodeport_service.go
  pkg/operator/controller/ingress/nodeport_service_test.go
  pkg/operator/controller/ingressclass/ingressclass_test.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/net/ipfamily.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1103 OCPBUGS-34413: Refine logging for accurate infra CR status updates
  pkg/operator/controller/ingress/controller.go
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1095 OCPBUGS-36465: Delete and recreate canary route to clear spec.host
  pkg/operator/controller/canary/route.go
  test/e2e/all_test.go
  test/e2e/canary_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1102 OCPBUGS-31664: Fix SyncLoadBalancerFailed status message of IngressController
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/status.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1099 [release-4.16] OCPBUGS-32887: Delete and recreate canary route to clear spec.host
  pkg/operator/controller/canary/route.go
  test/e2e/all_test.go
  test/e2e/canary_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1100 [release-4.15] OCPBUGS-36466: Allow operator to update Route spec.subdomain
  manifests/00-cluster-role.yaml
  pkg/operator/controller/canary/route.go
  test/e2e/all_test.go
  test/e2e/canary_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1101 [release-4.14] OCPBUGS-36467: Allow operator to update Route spec.subdomain
  manifests/00-cluster-role.yaml
  pkg/operator/controller/canary/route.go
  test/e2e/all_test.go
  test/e2e/canary_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1110 OCPBUGS-37627: Fix getRouteHost error handling
  test/e2e/canary_test.go
  test/e2e/client_tls_test.go
  test/e2e/operator_test.go
  test/e2e/router_compression_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1106 NE-1273: Add a watch to the ingress operator so it will recreate the gwapi crds
  .gitignore
  pkg/operator/controller/gatewayapi/controller.go
  test/e2e/gateway_api_test.go
  test/e2e/util_gatewayapi_test.go
Labels: lgtm, approved, jira/valid-reference
