Repository openshift/cluster-ingress-operator, pull requests merged in 2024-11, with the labels that each got.

#1148 CFE-1134: Watch infrastructure and update AWS tags
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/status_test.go
  test/e2e/all_test.go
  test/e2e/operator_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, jira/valid-reference

#1151 HOSTEDCP-2031: Use Client Certificate Authentication for ARO HCP deployments
  go.mod
  pkg/dns/azure/client/auth.go
  pkg/util/filewatcher/filewatcher.go
Labels: lgtm, approved, priority/critical-urgent, px-approved, jira/valid-reference

#1159 NE-1790: Enable Dynamic Configuration Manager feature gate
  go.mod
  go.sum
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/modules.txt
Labels: lgtm, approved, priority/critical-urgent, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1167 CORS-3755: AWS: Add Ingress LB IPs to Infra CR when in-cluster DNS is enabled
  go.mod
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/controller_test.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
