Repository openshift/cluster-ingress-operator, pull requests merged in 2025-01, with the labels that each got.

#1174 NE-1790: Follow up to enable Dynamic Configuration Manager feature gate
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, jira/valid-reference

#1165 OCPBUGS-41892: Single Watch on GWAPI CRD
  pkg/operator/controller/gatewayapi/controller.go
Labels: lgtm, approved, priority/backlog, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1176 NE-1260: Add Makefile target to run Gateway API conformance tests
  Makefile
  hack/gatewayapi-conformance.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1164 OCPBUGS-48780: Fix IBMCloud DNS Propagation Issues in E2E
  test/e2e/idle_connection_test.go
  test/e2e/operator_test.go
  test/e2e/util_gatewayapi_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
