Repository openshift/cluster-ingress-operator, pull requests merged in 2025-08, with the labels that each got.

#1246 NE-2108: Add OSSM channel and version override annotations
  cmd/ingress-operator/start.go
  hack/ossm-overrides.md
  manifests/02-deployment-ibm-cloud-managed.yaml
  manifests/02-deployment.yaml
  pkg/operator/config/config.go
  pkg/operator/controller/gatewayclass/controller.go
  pkg/operator/controller/gatewayclass/controller_test.go
  pkg/operator/controller/gatewayclass/istio.go
  pkg/operator/controller/gatewayclass/subscription.go
  pkg/operator/controller/gatewayclass/subscription_test.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/valid-reference

#1253 NE-2108: docs - correct Istio version format in ossm-overrides.md
  hack/ossm-overrides.md
Labels: lgtm, approved, jira/valid-reference

#1259 NO-JIRA: Add rikatz to OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1268 NE-2066: Set degraded=true when OSSM 3 can't be installed
  pkg/operator/controller/gatewayapi/controller.go
  pkg/operator/controller/gatewayapi/controller_test.go
  pkg/operator/controller/names.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/valid-reference

#1271 OCPBUGS-59139: Increase assertExpectedDNSRecords timeouts
  test/e2e/util_gatewayapi_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1267 OCPBUGS-53432: deflake TestIngressControllerCustomEndpoints by proper waiting for CCM to be ready
  test/e2e/operator_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
