Repository openshift/cluster-ingress-operator, pull requests merged in 2025-03, with the labels that each got.

#1192 NE-1953: Add Validating Admission Policy for Gateway API CRDs
  Makefile
  manifests/01-validating-admission-policy-binding.yaml
  manifests/01-validating-admission-policy.yaml
  test/e2e/all_test.go
  test/e2e/gateway_api_test.go
  test/e2e/util_gatewayapi_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#1199 NE-1981: Move controller test helpers to dedicated package
  Makefile
  pkg/operator/controller/gateway-service-dns/controller_test.go
  pkg/operator/controller/gatewayapi/controller_test.go
  pkg/operator/controller/route-metrics/controller_test.go
  pkg/operator/controller/test/util/fake.go
Labels: lgtm, approved, jira/valid-reference

#1112 NE-1907: Manage OSSM operator subscription manually to ensure a compatible version is installed
  cmd/ingress-operator/start.go
  manifests/00-cluster-role.yaml
  manifests/02-deployment-ibm-cloud-managed.yaml
  manifests/02-deployment.yaml
  pkg/operator/config/config.go
  pkg/operator/controller/gatewayclass/controller.go
  pkg/operator/controller/gatewayclass/subscription.go
  pkg/operator/controller/gatewayclass/subscription_test.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/valid-reference, priority/important-now

#1193 NE-1952: Pre-upgrade check for Gateway API CRD Management Succession
  pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_gatewayclasses.yaml
  pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_gateways.yaml
  pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_grpcroutes.yaml
  pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_httproutes.yaml
  pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_referencegrants.yaml
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/controller/test/crds/crds.go
  pkg/operator/controller/test/crds/crds_test.go
  pkg/operator/controller/test/crds/gateway-api/experimental/v1/gateway.networking.k8s.io_gateways.yaml
  pkg/operator/controller/test/crds/gateway-api/experimental/v1/gateway.networking.k8s.io_tcproutes.yaml
  pkg/operator/controller/test/crds/gateway-api/experimental/v1/gateway.networking.x-k8s.io_listenersets.yaml
  pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_gatewayclasses.yaml
  pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_gateways.yaml
  pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_httproutes.yaml
  pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_referencegrants.yaml
  pkg/operator/operator.go
  test/e2e/all_test.go
  test/e2e/gatewayapi_upgradeable_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-reference

#1200 NE-1953: Add experimental Gateway API group to Validating Admission Policy
  manifests/01-validating-admission-policy.yaml
  test/e2e/gateway_api_test.go
  test/e2e/util_gatewayapi_test.go
Labels: lgtm, approved, jira/valid-reference

#1196 NE-1951: Pre-upgrade Admin Gate for Gateway API CRD Management Succession
  pkg/operator/controller/gatewayapi-upgradeable/controller.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
  test/e2e/gatewayapi_upgradeable_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1197 CORS-3907: Update ingress operator to with custom endpoints
  pkg/dns/gcp/provider.go
  pkg/operator/controller/dns/controller.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1204 NE-1994: Add E2E test for Istio manual deployment
  test/e2e/gateway_api_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#933 NE-1277: status: Add Gateway API objects to relatedObjects
  pkg/operator/controller/status/controller.go
  pkg/operator/operator.go
  test/e2e/canary_test.go
  test/e2e/gateway_api_test.go
  test/e2e/operator_test.go
  test/e2e/util_gatewayapi_test.go
Labels: lgtm, approved, priority/important-soon, jira/valid-reference, acknowledge-critical-fixes-only
