Repository openshift/cluster-ingress-operator, pull requests merged in 2025-04, with the labels that each got.

#1208 NE-2008: Add GRPC conformance tests
  hack/gatewayapi-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#1203 OCPBUGS-53424: Wait for install plans to enter the "Requires Approval" phase before approving them
  pkg/operator/controller/gatewayclass/controller.go
  pkg/operator/controller/gatewayclass/subscription.go
  pkg/operator/controller/gatewayclass/subscription_test.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1211 OCPBUGS-54568: desiredIstio: Specify priorityClassName
  pkg/operator/controller/gatewayclass/istio.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1216 NE-2009: Move VAP to Default featureset
  manifests/01-validating-admission-policy-binding.yaml
  manifests/01-validating-admission-policy.yaml
Labels: lgtm, approved, jira/valid-reference

#1214 OCPBUGS-54650, OCPBUGS-54651, OCPBUGS-54652: desiredSubscription: Specify annotations and SCC
  go.mod
  go.sum
  pkg/operator/controller/gatewayclass/istio.go
  pkg/operator/controller/gatewayclass/subscription.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1213 NE-1957: Add Gateway API DNS Feature e2e tests
  test/e2e/gateway_api_test.go
  test/e2e/util_gatewayapi_test.go
Labels: lgtm, approved, jira/valid-reference

#1205 NE-1969: Set Degraded=True if unmanaged Gateway API CRDs exist
  pkg/operator/controller/gateway-service-dns/controller_test.go
  pkg/operator/controller/gatewayapi/controller.go
  pkg/operator/controller/gatewayapi/controller_test.go
  pkg/operator/controller/gatewayapi/crds.go
  pkg/operator/controller/gatewayapi/status.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/controller/test/util/fake.go
  test/e2e/gateway_api_test.go
  test/e2e/util_gatewayapi_test.go
Labels: lgtm, approved, jira/valid-reference

#1222 CNTRLPLANE-112: Remove ARO HCP MIv2 Authentication for Ingress Operator
  go.mod
  pkg/dns/azure/client/auth.go
  pkg/dns/azure/client/client.go
  pkg/util/filewatcher/filewatcher.go
Labels: lgtm, approved, jira/valid-reference
