Repository openshift/cluster-ingress-operator, pull requests merged in 2025-05, with the labels that each got.

#1232 OCPBUGS-55317: Check capabilities before watching OLM resource
  pkg/operator/controller/gatewayapi/controller.go
  pkg/operator/controller/gatewayapi/controller_test.go
  pkg/operator/controller/status/controller.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1223 [release-4.17] OCPBUGS-49702: Add support for IdleConnectionTerminationPolicy
  go.mod
  go.sum
  manifests/00-custom-resource-definition.yaml
  pkg/operator/controller/ingress/deployment.go
  pkg/operator/controller/ingress/deployment_test.go
  vendor/github.com/openshift/api/Dockerfile.ocp
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1217 OCPBUGS-54745: status: Conditionally add CRDs to relatedObjects
  pkg/operator/controller/status/controller.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
