Repository openshift/cluster-ingress-operator, pull requests merged in 2025-09, with the labels that each got.

#1273 OCPBUGS-60859: Fix logic on gatewayapi test cleanup
  test/e2e/gateway_api_test.go
  test/e2e/idle_connection_test.go
  test/e2e/util_gatewayapi_test.go
  test/e2e/util_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only, verified

#1278 NO-JIRA: Add davidesalerno to OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-reference, verified

#1281 NO-JIRA: Add bentito (btofel@redhat.com) to OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-reference, verified

#1242 OCPBUGS-55673: Remove IngressControllerLBSubnetsAWS featuregate
  pkg/operator/controller/ingress/controller.go
  pkg/operator/controller/ingress/load_balancer_service.go
  pkg/operator/controller/ingress/load_balancer_service_test.go
  pkg/operator/controller/ingress/status.go
  pkg/operator/controller/ingress/status_test.go
  pkg/operator/operator.go
  test/e2e/lb_subnets_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, verified
